### ISSUE TITLE
Fix error message when giving a bad manifest

### ISSUE THREAD

**Issue by m1ghtym0** [edgelesssys/marblerun#117]
If a manifest is passed to the cli `marblerun manifest set manifest.json $MARBLERUN` but the command fails du to some error in the manifest, the cli prints:

```
unable to set manifest: Server is not in expected state. Did you mean to update the manifest?
```

This is due handling all `http.StatusBadRequest` the same in `cli/cmd/manifestSet.go`:

```
	case http.StatusBadRequest:
		return fmt.Errorf("unable to set manifest: Server is not in expected state. Did you mean to update the manifest?")
```

**Comment by daniel-weisse** [comment]
The original idea was to notify the user if the manifest was already set, but since API now returns the full error this should probably be changed to just printing the error message returned by the coordinator.
