### ISSUE TITLE
[Coordinator] Stand-alone usage

### ISSUE THREAD

**Issue by dimakuv** [edgelesssys/marblerun#147]
Based on https://www.marblerun.sh/docs/getting-started/coordinator/, it looks like the Coordinator service can be used completely independently of the whole "Kubernetes mesh" part. Of course, each trusted application (e.g., SGX enclave) needs the "Marbles" component, but there seems to be no need to tie the deployment to Kubernetes.

In particular, I'm thinking about a simple scenario:
- One machine runs SGX application using Graphene (+ the Marble preload component)
- Another machine runs the Coordinator (with the JSON manifest containing only one package -- the SGX app)

Would that work? Or I would still need to install/run some dependencies for the Coordinator which are not strictly needed for my scenario?

**Comment by m1ghtym0** [comment]
Hi @dimakuv, yes that would work.

We provide some auto-configuration features for Marblerun in a Kubernetes context that are not available in this scenario:
* The Marble preload component needs to be configured manually with the address of the Coordinator machine.
* Also, the Coordinator and preload component need to be configured with the correct CN for their certificates.

Regarding remote attestation, we support only DCAP so far. This means that both machines need to have DCAP-capable hardware available and configured.

If there is anything missing or unclear in our documentation regarding the standalone setup, please let me know:-)
We focused a lot on Kubernetes lately, but it makes sense to have a designated page for a standalone scenario.

**Comment by dimakuv** [comment]
I am currently installing and experimenting with the Coordinator, based on the steps in https://github.com/edgelesssys/marblerun/blob/master/BUILD.md.

I will dump my findings and thoughts in this issue, if you don't mind.

First question: I am surprised that the Edgeless RT package is so huge. My Ubuntu informs me about 437 MB of required disk space, and 144 MB size of the `edgelessrt_0.2.3_amd64.deb` package. Why is Edgeless RT distribution so huge? What are the main components that take so much space?

```sh
$ sudo apt install ./edgelessrt_0.2.3_amd64.deb build-essential libssl-dev

The following NEW packages will be installed:
  edgelessrt
After this operation, 437 MB of additional disk space will be used.
Get:1 /home/dimakuv/edgelessrt_0.2.3_amd64.deb edgelessrt amd64 0.2.3 [144 MB]
```

UPDATE: Ok, you include the complete Go runtime and sources in this package, as well as some OpenEnclave files. Is there a particular reason to include all Go binaries & sources? It's not a big deal, just curious.

**Comment by m1ghtym0** [comment]
@thomasten ^

**Comment by dimakuv** [comment]
One more strange thing about this package. It installs the file `/opt/edgelessrt/share/openenclave/openenclaverc`. These are the contents of this file:
```
# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

# Update PKG_CONFIG_PATH.
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-install/share/pkgconfig

# Set CMake Config-package path
export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-install/lib/openenclave/cmake

# Update PATH.
export PATH=${PATH}:/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-install/bin
```

The paths don't make sense. There is no `/__w/` directory on my system. I've manually identified the correct paths (at least I think they are correct) and ended up with the following modified file:
```
# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

# Update PKG_CONFIG_PATH.
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/opt/edgelessrt/share/pkgconfig

# Set CMake Config-package path
export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/opt/edgelessrt/lib/openenclave/cmake

# Update PATH.
export PATH=${PATH}:/opt/edgelessrt/bin
```

After fixing these paths and reloading this file (via `. /opt/edgelessrt/share/openenclave/openenclaverc`), I was able to follow the HelloWorld guide (https://github.com/edgelesssys/edgelessrt/tree/master/samples/helloworld) and successfully run the enclave:
```
~/samples/helloworld/build$ erthost enclave.signed
[erthost] loading enclave ...
[erthost] entering enclave ...
[deventry] running in development mode
[deventry] invoking main
Hello world from the enclave!
Commandline arguments:
enclave.signed
```

Ok, so far so good. Now let me play with the Coordinator :)

**Comment by dimakuv** [comment]
Now I'm trying to build Marblerun (I cloned the GitHub repo https://github.com/edgelesssys/marblerun and following the build instructions in https://github.com/edgelesssys/marblerun/blob/master/BUILD.md).

Got the following error during build:
```sh
~/marblerun/build$ make

[ 50%] Built target sign-marble-test
Scanning dependencies of target marble-test-noenclave
can't load package: package /home/dimakuv/marblerun/cmd/marble-test: import "/home/dimakuv/marblerun/cmd/marble-test": cannot
import absolute path
CMakeFiles/marble-test-noenclave.dir/build.make:76: recipe for target 'CMakeFiles/marble-test-noenclave' failed
```

Exploring the contents of `CMakeFiles/marble-test-noenclave.dir/build.make:76` leads to this command:
```
CMakeFiles/marble-test-noenclave:
    go build -o marble-test-noenclave /home/dimakuv/marblerun/cmd/marble-test
```

Looking at the directory `/home/dimakuv/marblerun/cmd/marble-test`:
```sh
$ ls /home/dimakuv/marblerun/cmd/marble-test
main.go  mesh.go  mock.go
```

Each of these files contains normal relative/http Go imports. Meh, need to google what this error actually means.

**Comment by thomasten** [comment]
@dimakuv What's does `go version` say?

**Comment by dimakuv** [comment]
@thomasten 

```
$ go version
go version go1.10.4 linux/amd64
```

**Comment by thomasten** [comment]
You need 1.14 or newer

**Comment by dimakuv** [comment]
I'm still struggling with the build of the Marblerun repo.

Now I'm at this build error:
```
~/marblerun/build$ make
...
[ 90%] Generating coordinator-config.json
[100%] Built target sign-coordinator
Scanning dependencies of target cli
go: downloading github.com/c2h5oh/datasize v0.0.0-20200825124411-48ed595a09d2
... download many packages ...
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
# github.com/edgelesssys/ertgolib/erthost
../../pkg/mod/github.com/edgelesssys/ertgolib@v0.1.5-0.20210208080427-0d5e24e2f855/erthost/erthost.go:6:11: fatal error: openenclave/host_verify.h: No such file or directory
 // #include <openenclave/host_verify.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cli.dir/build.make:76: recipe for target 'CMakeFiles/cli' failed
```

This is the failing include: https://github.com/edgelesssys/ertgolib/blob/0d5e24e2f8559f5edf7b1dca5532c193a064d8d7/erthost/erthost.go#L6.

I have this file `openenclave/host_verify.h` in the installed Edgeless RT dir:
```
/opt/edgelessrt$ find . -name host_verify.h
./include/openenclave/host_verify.h
```

Which means that somehow the directory `/opt/edgelessrt/include` must be passed to go-build environment as the "C include dir". Let me try to find how and where this is done...

**Comment by thomasten** [comment]
As you already recognized, the openenclaverc file in the deb package is broken. I'm working on it. In the meantime, use this:
```
# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

# Update PKG_CONFIG_PATH.
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/opt/edgelessrt/share/pkgconfig

# Set CMake Config-package path
export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/opt/edgelessrt/lib/openenclave/cmake

# Update PATH.
export PATH=${PATH}:/opt/edgelessrt/bin

# EDG: Update CGO flags.
export CGO_CFLAGS="$CGO_CFLAGS -I/opt/edgelessrt/include"
export CGO_LDFLAGS="$CGO_LDFLAGS -L/opt/edgelessrt/lib/openenclave/host"
```

**Comment by dimakuv** [comment]
Thanks @thomasten.

So the fixes boiled down to two things:
1. Updating Google Go to the latest version.
2. Using the `openenclaverc` file you provided.

The build was successful after applying these. Thanks!

**Comment by dimakuv** [comment]
Now I'm testing the Coordinator + Marbles example from https://github.com/edgelesssys/marblerun/blob/master/BUILD.md#run. I'm currently doing it in simulation mode (`OE_SIMULATION=1`).

It looks like the example `manifest.json` contents (https://github.com/edgelesssys/marblerun/blob/master/BUILD.md#create-a-manifest) are not supported anymore:
```
~/marblerun$ curl -k --data-binary @manifest.json https://localhost:4433/manifest
{"status":"error","data":null,"message":"manifest misses value for SignerID in package backend"}
```

And as expected now, the Marble application could not run correctly (the Coordinator refused to activate it):
```
~/marblerun$ EDG_MARBLE_TYPE=server EDG_MARBLE_UUID_FILE=$PWD/server_uuid EDG_TEST_ADDR=localhost:8001 OE_SIMULATION=1 erthost build/marble-test-enclave.signed
...
[PreMain] 2021/04/28 08:53:58 activating marble of type server
panic: rpc error: code = FailedPrecondition desc = cannot accept marbles in current state

goroutine 17 [running, locked to thread]:
main.ert_meshentry_premain(0x7f79b5f06ce4, 0x7f79b5f06ce8)
        /home/dimakuv/marblerun/cmd/marble-test/mesh.go:27 +0x194
main._cgoexpwrap_ddb8d1ce0454_ert_meshentry_premain(0x7f79b5f06ce4, 0x7f79b5f06ce8)
        _cgo_gotypes.go:75 +0x37
```

**Comment by thomasten** [comment]
@dimakuv ERT includes a modified version of Go (ertgo). The files shipped are the same as in the official binary release of Go. The sources of Go's stdlib are required. Some others might be expendable. We didn't try, but just kept as close to the official release as possible.

**Comment by dimakuv** [comment]
@thomasten Thanks for the explanation. But then the build process used the Go binaries installed on my system, rather than the ones shipped with ERT? Did I miss some step to "overwrite" the paths to Go binaries?

**Comment by thomasten** [comment]
It uses go for binaries running on the host and ertgo for binaries running in the enclave.

**Comment by thomasten** [comment]
> t looks like the example `manifest.json` contents (https://github.com/edgelesssys/marblerun/blob/master/BUILD.md#create-a-manifest) are not supported anymore

Try with
```
		"backend": {
			"SecurityVersion": 1,
			"ProductID": 1,
			"Debug": true
		}
```
for now. We'll discuss what values we should use in this example. And thanks for finding all the errors in this process!

**Comment by dimakuv** [comment]
@m1ghtym0 @thomasten I can successfully run the example with Coordinator + Marble server + Marble Client in the simulation mode (`OE_SIMULATION=1`).

(**NOTE**: I had to modify the example `manifest.json` to add smth like `"SignerID": "5001c4b865c0eecb3cfafd2063de6f27567a9d97464416ee85823a0bfc5bec66"` to the `backend` package. I simply took this value from `build/marble-test-config.json`. Please update the example with these instructions at https://github.com/edgelesssys/marblerun/blob/master/BUILD.md#create-a-manifest.)

I have a proper SGX machine with FLC and DCAP support. I'm running everything on the same machine (i.e., localhost everywhere). I use the defaults and the commands from the BUILD document. I get the following error when running in the SGX mode:
```sh
# on coordinator side
~/marblerun$ erthost build/coordinator-enclave.signed
{"level":"info","ts":1619600796.2366774,"caller":"core/marbleapi.go:54","msg":"Received activation request","MarbleType":"serv
er"}
2021-04-28T02:06:36-0700.775818Z [(E)ERROR] tid(0x7f6d8e182700) | coordinator-enclave.signed:mbedtls_x509_crt_verify failed with The CRL is expired (flags=0x20)
 (oe_result_t=OE_VERIFY_CRL_EXPIRED) [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/crypto/mbedtls/cert.c:_mbedtls_x509_crt_verify:353]

... more error messages from OE, more or less same complaints as above ...

{"level":"info","ts":1619600796.7726774,"caller":"zap/options.go:203","msg":"finished unary call with code Unauthenticated","grpc.start_time":"2021-04-28T09:06:36Z","system":"grpc","span.kind":"server","grpc.service":"rpc.Marble","grpc.method":"Activate","peer.address":"127.0.0.1:36246","error":"rpc error: code = Unauthenticated desc = invalid 
quote","grpc.code":"Unauthenticated","grpc.time_ms":535.9990234375}

# on Marble server side

~/marblerun$ EDG_MARBLE_TYPE=server EDG_MARBLE_UUID_FILE=$PWD/server_uuid EDG_TEST_ADDR=localhost:800
1 erthost build/marble-test-enclave.signed
...
[PreMain] 2021/04/28 09:06:35 generating CSR
[PreMain] 2021/04/28 09:06:35 generating quote
[PreMain] 2021/04/28 09:06:36 activating marble of type server
panic: rpc error: code = Unauthenticated desc = invalid quote

goroutine 17 [running, locked to thread]:
main.ert_meshentry_premain(0x7fc4e191dce4, 0x7fc4e191dce8)
        /home/dimakuv/marblerun/cmd/marble-test/mesh.go:27 +0x194
main._cgoexpwrap_ddb8d1ce0454_ert_meshentry_premain(0x7fc4e191dce4, 0x7fc4e191dce8)
        _cgo_gotypes.go:75 +0x37
```

How is the Certificate Revocation List (CRL) generated? where do the expiration dates for it come from? Are you familiar with this error?

**Comment by thomasten** [comment]
I guess CRL comes from the PCCS, but I'm not familiar with it. Just tried on an Anzure VM and don't get this error. Maybe @m1ghtym0 or @flxflx know more about it.

**Comment by m1ghtym0** [comment]
I haven't seen this error, but it seems it is indeed related to the PCCS: https://github.com/openenclave/openenclave/issues/1842
Did you make sure the times on your machines are synced?
Are you running with a PCCS infrastructure? Is the PCCS up-to-date with the Intel SGX Root CA CRL endpoint?
In case you're running on Azure, is the `az-dcap-client` up-to-date?

**Comment by dimakuv** [comment]
Thanks for hints. I'm running locally on the same machine, its date is synched with the rest of the world.

I'm *not* using Azure. Instead, I am using my own locally installed PCCS (see e.g. https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md).

According to PCCS logs (`/opt/intel/sgx-dcap-pccs/logs/pccs_server.log`), it looks like PCCS is talking to the Intel web services and is up-to-date. But my PCCS itself was installed one year ago, so maybe it's just too old.

I'll ask around what happens there. I'll also update the DCAP/PCCS codebase to the latest releases and see how it goes. Thanks for the hints.

**Comment by dimakuv** [comment]
Ok, it was a lot of jiujitsu with my local PCCS, but I made it through. I'll keep some pointers for prosperity here.

- PCCS Design guide: https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/SGX_DCAP_Caching_Service_Design_Guide.pdf
- An example command to retrieve Intel Root CA CRL from PCCS:
    `curl --insecure --request GET --url https://localhost:8081/sgx/certification/v2/rootcacrl > rootca.crl`
- An example command to human-read the retrieved CRL:
    `openssl crl -inform PEM -text -noout -in rootca.crl`
- An example command to refresh all SGX collaterals in PCCS (**didn't work for me, see below**):
    `curl --insecure --request GET -H "admin-token: <my password>" --url  https://localhost:8081/sgx/certification/v2/refresh`

So my problem was that the Intel Root CA CRL was very old in my PCCS cache (stored in the SQLite database under `/opt/intel/sgx-dcap-pccs/pckcache.db`). In had the end-of-life date of `May 31 08:44:51 2020 GMT`; one year ago!

Asking PCCS politely to `refresh` the SGX collaterals (see above) didn't work out: all collaterals were updated **except the Root CA CRL**. I don't know if this is/was a bug in PCCS, but I informed the PCCS developers.

So I had to use brute force: removing `pckcache.db` and restarting PCCS. After that I was able to refresh and get the new Root CA CRL, with the end-of-life date of `Apr 26 13:37:47 2022 GMT`.

Now that I've overcome this obstacle, let's go back to Marblerun Coordinator again...

**Comment by dimakuv** [comment]
I guess I hit the dead-end on my local machine:
```
2021-04-29T03:08:20-0700.065635Z [(E)ERROR] tid(0x7fae797f5700) |
coordinator-enclave.signed:Platform TCB (2) is not up-to-date (oe_result_t=OE_TCB_LEVEL_INVALID) 
[/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/common/sgx/tcbinfo.c:oe_parse_tcb_info_json:742]
```

This seems fair because my local SGX machine wasn't updated. And I'm not eager to update its BIOS/firmware. I guess I'll need to move to "proper" MS Azure VMs...

**Comment by m1ghtym0** [comment]
@dimakuv Thanks a lot for going through this!
We're onto fixing the things on the Marblerun-side that popped up during this thread.
If it is ok with you I'll integrate some of your findings in the "standalone setup" page that we'll add to our docs soon?

**Comment by dimakuv** [comment]
> If it is ok with you I'll integrate some of your findings in the "standalone setup" page that we'll add to our docs soon?

Yes, of course. Thanks for your timely help and feedback!

**Comment by dimakuv** [comment]
I switched to an Azure SGX VM. Trying to run the Coordinator + Marbles example from 

Still bump into errors. Here is the Coordinator output:
```
dimakuv@sgx-ms-dcap2:~/marblerun$ erthost build/coordinator-enclave.signed
[erthost] loading enclave ...
[erthost] entering enclave ...
[meshentry] invoking premain
[meshentry] invoking main
{"level":"info","ts":1619776112.1056836,"caller":"coordinator/run.go:46","msg":"starting coordinator","version":"0.3.1","commit":"ee6fbe3871bc14cac8a4bd366d1404ec14c2723f"}
{"level":"info","ts":1619776112.1056836,"caller":"coordinator/run.go:56","msg":"creating the Core object"}
{"level":"info","ts":1619776112.1056836,"caller":"core/core.go:122","msg":"loading state"}
{"level":"info","ts":1619776112.1056836,"caller":"core/core.go:139","msg":"No sealed state found. Proceeding with new state."}
{"level":"info","ts":1619776112.1136837,"caller":"core/core.go:360","msg":"generating quote"}
Azure Quote Provider: libdcap_quoteprov.so [INFO]: Debug Logging Enabled
{"level":"info","ts":1619776112.1456838,"caller":"coordinator/run.go:71","msg":"starting the client server"}
{"level":"info","ts":1619776112.1456838,"caller":"coordinator/run.go:80","msg":"starting the marble server"}
{"level":"info","ts":1619776112.1456838,"caller":"server/server.go:252","msg":"starting client https server","address":":4433"}
{"level":"info","ts":1619776112.1456838,"caller":"coordinator/run.go:92","msg":"started gRPC server","grpcAddr":"[::]:2001"}
{"level":"info","ts":1619776137.3138347,"caller":"core/marbleapi.go:54","msg":"Received activation request","MarbleType":"server"}
{"level":"warn","ts":1619776137.3178349,"caller":"zap/options.go:203","msg":"finished unary call with code FailedPrecondition","grpc.start_time":"2021-04-30T09:48:57Z","system":"grpc","span.kind":"server","grpc.service":"rpc.Marble","grpc.method":"Activate","peer.address":"127.0.0.1:43766","error":"rpc error: code = FailedPrecondition desc = cannot accept marbles in current state","grpc.code":"FailedPrecondition","grpc.time_ms":4}
```

Notce the last message. This is when I tried to connect with the Marble Server. Here is the output of Marble Server:
```
dimakuv@sgx-ms-dcap2:~/marblerun$ EDG_MARBLE_TYPE=server EDG_MARBLE_UUID_FILE=$PWD/server_uuid EDG_TEST_ADDR=localhost:8001 erthost build/marble-test-enclave.signed
[erthost] loading enclave ...
[erthost] entering enclave ...
[meshentry] invoking premain
[PreMain] 2021/04/30 09:48:57 starting PreMain
[PreMain] 2021/04/30 09:48:57 fetching env variables
[PreMain] 2021/04/30 09:48:57 loading TLS Credentials
[PreMain] 2021/04/30 09:48:57 loading UUID
[PreMain] 2021/04/30 09:48:57 found UUID: 99083423-6bb5-48d2-a1a8-d4218a9b0f14
[PreMain] 2021/04/30 09:48:57 generating CSR
[PreMain] 2021/04/30 09:48:57 generating quote
Azure Quote Provider: libdcap_quoteprov.so [INFO]: Debug Logging Enabled
[PreMain] 2021/04/30 09:48:57 activating marble of type server
panic: rpc error: code = FailedPrecondition desc = cannot accept marbles in current state

goroutine 17 [running, locked to thread]:
main.ert_meshentry_premain(0x7f522191ece4, 0x7f522191ece8)
        /home/dimakuv/marblerun/cmd/marble-test/mesh.go:27 +0x194
main._cgoexpwrap_ddb8d1ce0454_ert_meshentry_premain(0x7f522191ece4, 0x7f522191ece8)
        _cgo_gotypes.go:75 +0x37
```

Note that I first ran the example with `OE_SIMULATION=1` and that thing worked. Then I tried to move to the SGX mode, for which I needed to remove the `marblerun-coordinator-data/` files. I removed that directory completely, and now I always have an empty dir:
```
dimakuv@sgx-ms-dcap2:~/marblerun$ ls marblerun-coordinator-data/
< empty >
```

Is this normal? Why is there no `seal_key` created as previously?

**Comment by dimakuv** [comment]
Ok, apparently I forgot to upload the `manifest.json` file into the Coordinator after I removed `marblerun-coordinator-data`. Which makes sense -- the Coordinator doesn't have any "known good enclaves" data to work with, so the Coordinator cannot accept any requests from Marbles. Though `cannot accept marbles in current state` message is a bit cryptic -- maybe mention that there is no manifest file uploaded yet into the Coordinator?

**Comment by dimakuv** [comment]
But even after all this, I still can't run the example. Now I'm working in SGX mode, and the Coordinator says this:
```
dimakuv@sgx-ms-dcap2:~/marblerun$ AZDCAP_DEBUG_LOG_LEVEL="WARNING" erthost build/coordinator-enclave.signed
[erthost] loading enclave ...
[erthost] entering enclave ...
[meshentry] invoking premain
[meshentry] invoking main
{"level":"info","ts":1619776971.1508439,"caller":"coordinator/run.go:46","msg":"starting coordinator","version":"0.3.1","commit":"ee6fbe3871bc14cac8a4bd366d1404ec14c2723f"}
{"level":"info","ts":1619776971.154844,"caller":"coordinator/run.go:56","msg":"creating the Core object"}
{"level":"info","ts":1619776971.154844,"caller":"core/core.go:122","msg":"loading state"}
{"level":"info","ts":1619776971.154844,"caller":"core/core.go:139","msg":"No sealed state found. Proceeding with new state."}
{"level":"info","ts":1619776971.1628442,"caller":"core/core.go:360","msg":"generating quote"}
Azure Quote Provider: libdcap_quoteprov.so [INFO]: Debug Logging Enabled
{"level":"info","ts":1619776971.1948445,"caller":"coordinator/run.go:71","msg":"starting the client server"}
{"level":"info","ts":1619776971.1948445,"caller":"server/server.go:252","msg":"starting client https server","address":":4433"}
{"level":"info","ts":1619776971.1948445,"caller":"coordinator/run.go:80","msg":"starting the marble server"}
{"level":"info","ts":1619776971.1988444,"caller":"coordinator/run.go:92","msg":"started gRPC server","grpcAddr":"[::]:2001"}

# at this point I upload the manifest.json file with the correctly modified "SignerID"
127.0.0.1 - - [30/Apr/2021:10:03:08 +0000] "POST /manifest HTTP/2.0" 200 33

# at this point I try to active Marble Server, and it fails
{"level":"info","ts":1619777016.219115,"caller":"core/marbleapi.go:54","msg":"Received activation request","MarbleType":"server"}
{"level":"info","ts":1619777016.2991154,"caller":"zap/options.go:203","msg":"finished unary call with code Unauthenticated","grpc.start_time":"2021-04-30T10:03:36Z","system":"grpc","span.kind":"server","grpc.service":"rpc.Marble","grpc.method":"Activate","peer.address":"127.0.0.1:45152","error":"rpc error: code = Unauthenticated desc = invalid quote","grpc.code":"Unauthenticated","grpc.time_ms":80}
```

So the Coordinator complains with an error `error = Unauthenticated desc = invalid quote`.

At the same time, I don't see anything special in the Azure OpenEnclave DCAP output. (I ran the same with `AZDCAP_DEBUG_LOG_LEVEL="INFO"`, and Azure DCAP seemed to do the right things -- go to the Azure caching server, fetch some SGX collaterals, etc.).

**Comment by thomasten** [comment]
Can you remove `Infrastructures` from the manifest? Then you may get an `invalid quote` error with a reason. (Kind of a bug that we don't print the reason in the other case.)

**Comment by dimakuv** [comment]
@thomasten Thanks, this is interesting. I get some more info now:
```
dimakuv@sgx-2021:~/marblerun$ EDG_MARBLE_TYPE=server EDG_MARBLE_UUID_FILE=$PWD/server_uuid EDG_TEST_ADDR=localhost:8001 erthost build/marble-test-enclave.signed
[erthost] loading enclave ...
[erthost] entering enclave ...
[meshentry] invoking premain
[PreMain] 2021/04/30 10:53:28 starting PreMain
[PreMain] 2021/04/30 10:53:28 fetching env variables
[PreMain] 2021/04/30 10:53:28 loading TLS Credentials
[PreMain] 2021/04/30 10:53:28 loading UUID
[PreMain] 2021/04/30 10:53:28 found UUID: 9528133a-581b-4c5c-9c40-938d7da094cf
[PreMain] 2021/04/30 10:53:28 generating CSR
[PreMain] 2021/04/30 10:53:28 generating quote
Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retrieve environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
[PreMain] 2021/04/30 10:53:28 activating marble of type server
panic: rpc error: code = Unauthenticated desc = invalid quote: PackageProperties not compliant:
{true 8af790f9bb37681bd1aafdac6c8f12f03264e3fbb496e175ec11ffdee8f20fcc 8c579bb6f6c3bcb839d7df31a9b2cbaad9bdd092b0d1e210946e73aaffd62903 0x7efc1432c7a0 0x7efc141e96d8}
{false  8c579bb6f6c3bcb839d7df31a9b2cbaad9bdd092b0d1e210946e73aaffd62903 0x7efc141f78e0 0x7efc141f78d8}
```

And my measurements of the sample SGX enclave are like this:
```
dimakuv@sgx-2021:~/marblerun$ cat build/marble-test-config.json                                                               {
        "SecurityVersion": 1,
        "ProductID": 1,
        "UniqueID": "8af790f9bb37681bd1aafdac6c8f12f03264e3fbb496e175ec11ffdee8f20fcc",
        "SignerID": "8c579bb6f6c3bcb839d7df31a9b2cbaad9bdd092b0d1e210946e73aaffd62903"
}
```

Hm, how do I decipher this message?

**Comment by thomasten** [comment]
It says that your manifest does not allow debug enclaves. You have to add `"Debug": true` to the `backend` package. (And we have to add it to the doc. Regarding the error messages, we already have a ticket for improving them and should probably prioritize it.)

**Comment by dimakuv** [comment]
Hurray! So awesome that Marblerun is open-source and I can easily find the corresponding code:
- https://github.com/edgelesssys/marblerun/blob/787f8458008197a41437bf38a3bb392ef95fa6e7/coordinator/quote/ert.go
- https://github.com/edgelesssys/marblerun/blob/787f8458008197a41437bf38a3bb392ef95fa6e7/coordinator/quote/ertvalidator/ertvalidator.go

So it's easy to deduce that the `true` and `false` in the error message in the previous post concerns `Debug enclave` property. Apparently, I should add `Debug: true` to the `manifest.json`, like this:
```
                "backend": {
                        "Debug": true,
                        "UniqueID": "8af790f9bb37681bd1aafdac6c8f12f03264e3fbb496e175ec11ffdee8f20fcc"
                }
```

And it worked!

**Comment by dimakuv** [comment]
@m1ghtym0 @thomasten Another quick design question.

The Coordinator must be initialized with the `manifest.json` file.

1. In all examples, this file is sent using `curl` and without any password/authentication. Is this the final design, or will it be changed? If this is final, then what is the rationale for this seemingly insecure initialization?

2. It seems that the Coordinator accepts the `manifest.json` file only once, seals it, and never accepts any other manifest. Is this correct?
    - I know that there are `/recover` and `/update` REST endpoints to change/update the manifest partly, and these endpoints are protected by the Admin certificate (which is provisioned during the very first `curl ... /manifest` invocation). My question is not about these endpoints, but about the very first time the manifest is loaded.

**Comment by dimakuv** [comment]
Another quick update: HelloWorld Graphene examples (from https://www.marblerun.sh/docs/tasks/build-service-graphene/ and https://github.com/edgelesssys/marblerun/tree/master/samples/graphene-hello) work as expected. Thanks for these examples, very easy to follow!

**Comment by m1ghtym0** [comment]
> @m1ghtym0 @thomasten Another quick design question.
> 
> The Coordinator must be initialized with the `manifest.json` file.
> 
> 1. In all examples, this file is sent using `curl` and without any password/authentication. Is this the final design, or will it be changed? If this is final, then what is the rationale for this seemingly insecure initialization?

This is our final design, the reasoning is the following: 

* Before uploading a manifest Marblerun is basically raw, anyone with access to the client API can "claim" the cluster by uploading a manifest
* After uploading a manifest, Marblerun is initialized and "locked-in". The manifest can't be changed by anybody
* The initialization is insecure in the sense that somebody with access to the client API could race this process and upload a different manifest
    * We argue that trust is always established through the remote attestation process. This includes verifying the manifest in place. Hence, such "attack" would be obvious to any owner/client.
    * We could protect the initialization, but the question is how would credentials be shared with the Coordinator? Considering there is no point in time at the deployment phase where this would happen in a trusted way, we would need the remote attestation of the manifest anyway

> 2. It seems that the Coordinator accepts the `manifest.json` file only once, seals it, and never accepts any other manifest. Is this correct?
>    
>    * I know that there are `/recover` and `/update` REST endpoints to change/update the manifest partly, and these endpoints are protected by the Admin certificate (which is provisioned during the very first `curl ... /manifest` invocation). My question is not about these endpoints, but about the very first time the manifest is loaded.

This is correct. Updates are critical because we believe they are an essential feature in production. However, they need to be carefully implemented so that they don't break the trust of third parties. Right now we only allow to bump the SecurityVersion of an enclave (which of course doesn't protect much against misuse of updates) and we offer a certificate-based solution for clients to immediately notice when this happens.

**Comment by dimakuv** [comment]
> We argue that trust is always established through the remote attestation process. This includes verifying the manifest in place. Hence, such "attack" would be obvious to any owner/client.

Ok, makes sense. So you mean that the owner/clients know the "correct" manifest contents, and before establishing trust in the Coordinator, they issue `curl --cacert marblerun.crt "https://$MARBLERUN/manifest" | jq '.data.ManifestSignature' --raw-output` to get the SHA256 hash of the manifest file, and they compare against their known "correct" manifest hash.

Thanks for explanations! I think I understand all the internals (required for stand-alone usage of the Coordinator).

**Comment by m1ghtym0** [comment]
Thanks again @dimakuv for walking through this, helped a lot:-)
We've added a [deployment section](https://github.com/edgelesssys/marblerun.sh/pull/41) and a more [detailed explanation](https://github.com/edgelesssys/marblerun.sh/pull/48) of the chain of trust in Marblerun.
I'm closing this now.
