### ISSUE TITLE
[premain-Graphene] `posix_spawn` is slow and could be replaced with `execve`

### ISSUE THREAD

**Issue by dimakuv** [edgelesssys/marblerun#151]
I just noticed that `premain-graphene` code uses `posix_spawn()`. On Linux-x64, this is implemented via the combination of `vfork() + execve()`.

In Graphene, `vfork()` is a slow system call because it must create a new SGX enclave and securely copy the complete enclave-memory state from the parent enclave to the new child enclave.

However, `execve()` in Graphene is a very fast system call because there is no need to create a new enclave -- the parent enclave "becomes" the child enclave.

So in the below line you could actually use `execve` instead of `posix_spawn`: https://github.com/edgelesssys/marblerun/blob/211bd99818dee8deeb69da435fbe58f6d9854c56/cmd/premain-graphene/main.go#L44

And then everything would be fast, and you won't need two separate ways of running the pre-main functionality of Marbles.

This will also simplify your examples and the tutorials and the README: https://github.com/edgelesssys/marblerun/tree/master/samples/graphene-hello

You will get rid of what you call the `preload` method and only keep the `spawn` method which will not have the disadvantage of being slow.

**Comment by flxflx** [comment]
Sounds great. Thank you for all the input @dimakuv!

**Comment by Nirusu** [comment]
Yup, it seems much faster than the spawn method, and being able to streamline our samples definitely is a huge plus.

I implemented them in #153, many thanks for the suggestion!
