### ISSUE TITLE
Emojivoto test app: environment variable not set: EDG_MARBLE_COORDINATOR_ADDR

### ISSUE THREAD

**Issue by prateeksahu** [edgelesssys/marblerun#176]
Hi Team,
I was looking into SGX kubernetes deployment setups and came across your design. While following the steps on your quickstart doc (https://www.marblerun.sh/docs/getting-started/quickstart/), I faced crashed emojivoto pods (emoji-0, voting-0 and web-0).

I am using kubernetes 1.20 (with minikube) on Ubuntu 20.04. I am using helm3 in my setup.

coordinator pods are up and running fine, but the application pods are stuck at CrashLoopBackOff. Following are logs for emoji-0. Please advice what might be the issue here. Thanks
``` 
> ~/w/r/emojivoto   main  kubectl logs emoji-0 -n emojivoto
[PreMain] 2021/06/04 19:58:50 starting PreMain
[PreMain] 2021/06/04 19:58:50 fetching env variables
[PreMain] 2021/06/04 19:58:50 environment variable not set: EDG_MARBLE_COORDINATOR_ADDR
[erthost] running in simulation mode
[erthost] loading enclave ...
[erthost] entering enclave ...
```
All pods:
```
AMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
emojivoto     emoji-0                                  0/1     CrashLoopBackOff   85         6h56m
emojivoto     vote-bot-7b8d4974dc-wd9df                1/1     Running            0          6h56m
emojivoto     voting-0                                 0/1     CrashLoopBackOff   86         6h56m
emojivoto     web-0                                    0/1     CrashLoopBackOff   86         6h56m
kube-system   coredns-74ff55c5b-vjscd                  1/1     Running            0          29h
kube-system   etcd-marble                              1/1     Running            0          29h
kube-system   kube-apiserver-marble                    1/1     Running            0          29h
kube-system   kube-controller-manager-marble           1/1     Running            0          29h
kube-system   kube-proxy-kzd64                         1/1     Running            0          29h
kube-system   kube-scheduler-marble                    1/1     Running            0          29h
kube-system   storage-provisioner                      1/1     Running            1          29h
marblerun     marble-injector-755558cb77-nhv54         1/1     Running            0          29h
marblerun     marblerun-coordinator-668d8d687d-mmzpq   1/1     Running            0          29h
```

**Comment by daniel-weisse** [comment]
Hi @prateeksahu, thanks for reaching out!

As you can see from the logs, the `EDG_MARBLE_COORDINATOR_ADDR` env variable is missing from the pod.
This variable should be automatically injected into the emojivoto pods via the `marble-injector`.
To enable this feature we first need to annotate the emojivoto namespace:
```bash
kubectl create namespace emojivoto
marblerun namespace add emojivoto
```
Once this is done, all pods starting in the emojivoto namespace will have the variable set with the appropriate value.
When we now install emojivoto, everything should run as expected.

This step was previously missing in the quickstart section, but is fixed now.

For a more in depth installation of emojivoto you can also check out our github repository: https://github.com/edgelesssys/emojivoto

**Comment by prateeksahu** [comment]
Thank you for the reply @daniel-weisse . It fixed the issue. I realized that the env variable was missing but wasn't sure what was needed to be done.
I would also point out that if we are creating the namespace emojivoto already, then maybe the 
`helm install -f ./kubernetes/nosgx_values.yaml emojivoto ./kubernetes --create-namespace -n emojivoto` command can be changed to just 
`helm install -f ./kubernetes/nosgx_values.yaml emojivoto ./kubernetes`.
Anyways this issue is fixed, hence closing the issue.
