### ISSUE TITLE
Coordinator and Injector pods stuck at pending

### ISSUE THREAD

**Issue by ratnadeepb** [edgelesssys/marblerun#180]
**Describe the bug**
I attempted to deploy marblerun in simulation mode in an Ubuntu 20.04 LTS virtual machine following the [Quick Start](https://www.marblerun.sh/docs/getting-started/quickstart/) documentation. My understanding is that the simulation mode does not require SGX. However, both `Coordinator` and `injector` pods are stuck with pending status.

The virtual machine is running a single node K8 1.21 cluster and the node has been untainted.

**To reproduce**
1. Create a Kubernetes cluster
2. Install marblerun
3. `marblerun install --simulation`

**Expected behavior**
The injector and coordinator pods successfully deployed.

**Screenshots**

**Environment:**
 - Marblerun version: 0.3.2
 - Edgeless RT version:
 - Go version:

**Additional context**

**Comment by m1ghtym0** [comment]
Hi @ratnadeepb 

Thanks for reaching out!
You can run in Marblerun in simulation mode without SGX.
If your pods stay pending, it is most likely a  lack of resources.
Can you provide more details? Please send us the pod descriptions (`kubectl describe pods ${POD_NAME}`).

**Comment by ratnadeepb** [comment]
Pods Description:
`Name:           marblerun-coordinator-656b9c5cf6-m7p4x
Namespace:      marblerun
Priority:       0
Node:           <none>
Labels:         edgeless.systems/control-plane-component=coordinator
                edgeless.systems/control-plane-ns=marblerun
                pod-template-hash=656b9c5cf6
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/marblerun-coordinator-656b9c5cf6
Containers:
  coordinator:
    Image:       ghcr.io/edgelesssys/coordinator:v0.3.2
    Ports:       4433/TCP, 2001/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get https://:4433/status delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:   http-get https://:4433/status delay=0s timeout=1s period=10s #success=1 #failure=7
    Environment:
      EDG_COORDINATOR_MESH_ADDR:    0.0.0.0:2001
      EDG_COORDINATOR_CLIENT_ADDR:  0.0.0.0:4433
      EDG_COORDINATOR_DNS_NAMES:    localhost,coordinator-mesh-api,coordinator-client-api,coordinator-mesh-api.marblerun,coordinator-client-api.marblerun,coordinator-mesh-api.marblerun.svc.cluster.local,coordinator-client-api.marblerun.svc.cluster.local
      EDG_COORDINATOR_SEAL_DIR:     /coordinator/data/
      OE_SIMULATION:                1
    Mounts:
      /coordinator/data from coordinator-pv-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x2bw8 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  coordinator-pv-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  coordinator-pv-claim
    ReadOnly:   false
  kube-api-access-x2bw8:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              beta.kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  12h                  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  12h                  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  12h (x166 over 14h)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  55s (x5 over 4m57s)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.`

**Comment by m1ghtym0** [comment]
```
Warning FailedScheduling 12h default-scheduler 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
Warning FailedScheduling 12h default-scheduler 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
Warning FailedScheduling 12h (x166 over 14h) default-scheduler 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
Warning FailedScheduling 55s (x5 over 4m57s) default-scheduler 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.`
```

Your cluster can't provide a volume for the [Coordinator's PVC](https://github.com/edgelesssys/helm/blob/main/marblerun-coordinator/templates/coordinator.yaml#L78).
You can set a [custom storage class for the Coordinator](https://github.com/edgelesssys/helm/blob/main/marblerun-coordinator/templates/coordinator.yaml#L78) (similar for the marble-injector).

What's your current default storage class (`kubectl get storageclass`)?
If you don't have a storage class you can set it to [local](https://kubernetes.io/docs/concepts/storage/storage-classes/#local) and create the PVs [manually](https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/#how-to-use-a-local-persistent-volume).

**Comment by ratnadeepb** [comment]
So I copy pasted the storage class yaml. Then created a PV:
`NAME              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                           STORAGECLASS   REASON   AGE
data-consul-pv0   10Gi       RWO            Recycle          Available   marblerun/data-marblerun-pvc0   manual                  14s
`
The issue is still the same.

**Comment by m1ghtym0** [comment]
Your `PV` seems to be successfully claimed by the Coordinator.
Can you show the current status?

**Comment by ratnadeepb** [comment]
Status is still the same:
`NAME                                     READY   STATUS    RESTARTS   AGE
marble-injector-755558cb77-dqbbv         1/1     Running   1          16h
marblerun-coordinator-656b9c5cf6-m7p4x   0/1     Pending   0          16h`

Description:
`Name:           marblerun-coordinator-656b9c5cf6-m7p4x
Namespace:      marblerun
Priority:       0
Node:           <none>
Labels:         edgeless.systems/control-plane-component=coordinator
                edgeless.systems/control-plane-ns=marblerun
                pod-template-hash=656b9c5cf6
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/marblerun-coordinator-656b9c5cf6
Containers:
  coordinator:
    Image:       ghcr.io/edgelesssys/coordinator:v0.3.2
    Ports:       4433/TCP, 2001/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get https://:4433/status delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:   http-get https://:4433/status delay=0s timeout=1s period=10s #success=1 #failure=7
    Environment:
      EDG_COORDINATOR_MESH_ADDR:    0.0.0.0:2001
      EDG_COORDINATOR_CLIENT_ADDR:  0.0.0.0:4433
      EDG_COORDINATOR_DNS_NAMES:    localhost,coordinator-mesh-api,coordinator-client-api,coordinator-mesh-api.marblerun,coordinator-client-api.marblerun,coordinator-mesh-api.marblerun.svc.cluster.local,coordinator-client-api.marblerun.svc.cluster.local
      EDG_COORDINATOR_SEAL_DIR:     /coordinator/data/
      OE_SIMULATION:                1
    Mounts:
      /coordinator/data from coordinator-pv-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x2bw8 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  coordinator-pv-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  coordinator-pv-claim
    ReadOnly:   false
  kube-api-access-x2bw8:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              beta.kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  4m40s (x92 over 90m)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.`

**Comment by ratnadeepb** [comment]
Ok I think, I might have figured out the issue - I changed the claim name to `coordinator-pv-claim` and that seems to have fixed the issue.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-marblerun-pv0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: marblerun
    name: coordinator-pv-claim
  hostPath:
    path: "/mnt/data"
```
