### ISSUE TITLE
compiling graphene nginx in simulation mode

### ISSUE THREAD

**Issue by ratnadeepb** [edgelesssys/marblerun#181]
**Describe the bug**
marblerun is running in `simulation` mode in a single node K8s cluster. 
My questions/issues are as follows:
1. Is it possible to compile and run the nginx app in this case?
2. If possible, then should I use `make` or `make SGX=1|0`?
3. For any of these commands, the following error is received:
`make: *** No rule to make target '/home/ratnadeepb/graphene/Examples/common_tools/get_deps.sh', needed by 'trusted-libs'.  Stop.`

**To reproduce**
1. Create a marblerun simulation cluster
2. Clone and make graphene
3. Following instructions to build nginx for marblerun

**Expected behavior**
Expect build to complete???

**Screenshots**

**Environment:**
 - Marblerun version: 0.3.2
 - Edgeless RT version:
 - Go version:

**Additional context**

**Comment by m1ghtym0** [comment]
Hi @ratnadeepb,

> * Is it possible to compile and run the nginx app in this case?

Yes, you need to compile the nginx Graphene enclave for simulation mode.
> * If possible, then should I use `make` or `make SGX=1|0`?
> * For any of these commands, the following error is received:
>   `make: *** No rule to make target '/home/ratnadeepb/graphene/Examples/common_tools/get_deps.sh', needed by 'trusted-libs'.  Stop.`

You need `make SGX=0` to build the Graphen enclave in simulation mode.
Do you have a working Graphene setup? They have a [quickstart ](https://graphene.readthedocs.io/en/latest/quickstart.html#quick-start-without-sgx-support) to get you started.
We have this as a prerequisite in our [example](https://github.com/edgelesssys/marblerun/tree/master/samples/graphene-nginx#graphene-nginx-example):
> Prerequisite: Graphene is set up and the original nginx example is working. You will need hardware with Intel SGX support.

Make sure your Graphene path points to your Graphene installation:
```
export GRAPHENEDIR=[PATH To Your Graphene Folder]
```

**Comment by ratnadeepb** [comment]
ok. that sounds super. the `GRAPHENEDIR` path is correct. However, this file - `graphene/Examples/common_tools/get_deps.sh` - does not exist. That is what has me confused.

**Comment by m1ghtym0** [comment]
`~/graphene` is the default Graphene directory. That's why it's pointing there.

**Comment by ratnadeepb** [comment]
I meant to say that's where my graphene installation is too. That file physically does not exist:
```
ls ~/graphene/Examples/common_tools/
benchmark-http.sh
```
 - it doesn't exist in the Graphene repo too - https://github.com/oscarlab/graphene/tree/master/Examples/common_tools

**Comment by m1ghtym0** [comment]
Ah, this seems to be a change in Graphene. Checkout Graphene @ https://github.com/oscarlab/graphene/commit/f54d9f1c97abe4de99074f44e181f2e424df9209 and try again.
I'll add a ticket to pin this to an old Graphene version or update the build.

**Comment by ratnadeepb** [comment]
So if we are trying out this example in the simulation mode, do the rest of the steps remain the same? Because, I am receiving this error:
```
$ erthost ../../build/coordinator-enclave.signed
[erthost] loading enclave ...
2021-06-09T13:04:59-0400.555300Z [(H)ERROR] tid(0x7ff67fb0abc0) | oe_fopen failed path=../../build/coordinator-enclave.signed mode=rb
 [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/fopen.c:oe_fopen:18]
2021-06-09T13:04:59-0400.555309Z [(H)ERROR] tid(0x7ff67fb0abc0) | :OE_NOT_FOUND [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/sgx/load.c:_get_image_type:23]
2021-06-09T13:04:59-0400.555312Z [(H)ERROR] tid(0x7ff67fb0abc0) | :OE_NOT_FOUND [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/sgx/load.c:oe_load_enclave_image:56]
2021-06-09T13:04:59-0400.555314Z [(H)ERROR] tid(0x7ff67fb0abc0) | :OE_FAILURE [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/sgx/create.c:oe_sgx_build_enclave:884]
2021-06-09T13:04:59-0400.555317Z [(H)ERROR] tid(0x7ff67fb0abc0) | :OE_FAILURE [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/sgx/create.c:oe_create_enclave:1263]
2021-06-09T13:04:59-0400.555360Z [(H)ERROR] tid(0x7ff67fb0abc0) | oe_create_enclave failed. (Set OE_SIMULATION=1 for simulation mode.) [/__w/edgelessrt/edgelessrt/src/tools/erthost/erthost.cpp:main:163]
```

Basically, this file `coordinator-enclave.signed` does not exist!

**Comment by Nirusu** [comment]
@m1ghtym0 Please don't pin against an old version of Graphene, we should rather update our Samples here in this case. Plus we should also switch to using the new commands (e.g. `graphene-sgx`) instead of calling `pal-loader` like before.

@ratnadeepb 
You said you could get the "Hello World!" sample running... the Coordinator step is the same!

- If you got the Marblerun Coordinator already running in K8s, you should be able to just skip this step (assuming ports are exposed correctly).
- Otherwise the given path assumes that you built the Coordinator yourself from our repo. This should be in "../../build/coordinator-enclave.signed" when you used "build" as the build directory and are currently in the "graphene-hello" directory.
- In case you used the prebuilt run here from GitHub, just use the path to the downloaded "coordinator-enclave.signed" executable you downloaded.

**Comment by ratnadeepb** [comment]
My apologies, I meant the graphene "hello world". I tried the first option, didn't work for me - the port is closed. The second option - I checked the build dir in graphene and that file does not exist. For the downloadable binaries, would it be possible to provide a link?

**Comment by Nirusu** [comment]
I know, I also meant the Graphene "Hello World" sample ;) It includes the same "launch coordinator" step as the other one, that's why I'm baffled why this one works but the nginx sample does not.

Here you can download the prebuilt version:
https://github.com/edgelesssys/marblerun/releases/download/v0.3.2/coordinator-enclave.signed

**Comment by ratnadeepb** [comment]
alright, so `graphene-direct nginx` from inside the nginx folder works. I didn't think it was running through marblerun. I will try the prebuilt version.

**Comment by Nirusu** [comment]
Normally that should trigger Marblerun's Premain process, as our sample has it set as the entry point.

Can you see any lines in your terminal starting with [Premain]? If yes, that means nginx starts with Marblerun. And if it actually launches nginx and doss not abort within the Premain part, it means it successfully authenticated with a running Coordinator.

**Comment by ratnadeepb** [comment]
In that case, I don't think it is running with marblerun. I wonder why! I didn't have the time to look back at the k8s coordinator deployment. I will try to do that tomorrow. In the meantime, let me try with the prebuilt version.

**Comment by ratnadeepb** [comment]
I could run the prebuilt coordinator but trying to run nginx fails with the following error: `panic: open /dev/attestation/protected_files_key: permission denied`. The `/dev/attestation` folder is missing in my system.

```
$ EDG_MARBLE_TYPE=frontend EDG_MARBLE_COORDINATOR_ADDR=localhost:2001 EDG_MARBLE_UUID_FILE=uuid EDG_MARBLE_DNS_NAMES=localhost SGX=0 ./pal_loader nginx
WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Forwarding host environment variables to the app is enabled. Don't use this configuration in production!
[PreMain] 2021/06/09 19:21:59 starting PreMain
[PreMain] 2021/06/09 19:21:59 fetching env variables
[PreMain] 2021/06/09 19:21:59 loading TLS Credentials
[PreMain] 2021/06/09 19:21:59 loading UUID
[PreMain] 2021/06/09 19:21:59 found UUID: 1d165313-9b29-46b3-baa3-772beb2ba2f8
[PreMain] 2021/06/09 19:21:59 generating CSR
[PreMain] 2021/06/09 19:21:59 generating quote
[PreMain] 2021/06/09 19:21:59 failed to get quote: open /dev/attestation/user_report_data: permission denied. Proceeding in simulation mode
[PreMain] 2021/06/09 19:21:59 activating marble of type frontend
panic: open /dev/attestation/protected_files_key: permission denied

goroutine 1 [running]:
main.main()
	/home/moritz/edgeless/marblerun/cmd/premain-graphene/main.go:33 +0x2f7
```

Finally, is there some documentation that does a detailed walk-through of the workflow - the sequence of events in the coordinator and the injector?

**Comment by m1ghtym0** [comment]
Ok, there seems to be a bit of confusion here let me try to sort things out a bit.
Our Graphene examples are all just for a real SGX scenario for the sake of simplicity.
If you want to run them in simulation mode you have to consider two things.
1. Run Marblerun in simulation mode
2. Build and run Graphene enclaves in simulation mode

> So if we are trying out this example in the simulation mode, do the rest of the steps remain the same? Because, I am receiving this error:

You're trying to run Marblerun in standalone mode.
We have a [guide ](https://www.marblerun.sh/docs/deployment/standalone/) for this.
You need to either build it from source, this is where the path points to, or you can download the binaries from our latest release. See the guide for reference.

If you want to run in simulation mode you need the Coordinator simulation mode. You can do this by setting`OE_SIMULATION`.
```
OE_SIMULATION=1 erthost ../../build/coordinator-enclave.signed
```


> In that case, I don't think it is running with marblerun. I wonder why! I didn't have the time to look back at the k8s coordinator deployment. I will try to do that tomorrow. In the meantime, let me try with the prebuilt version.

Do I understand you correctly that you build the original Graphene example from the Graphene repository?
In that case, there was no Marble-code injected.
You need to build it from our repository as described in the [example](https://github.com/edgelesssys/marblerun/tree/master/samples/graphene-nginx).

> I could run the prebuilt coordinator but trying to run nginx fails with the following error: panic: open /dev/attestation/protected_files_key: permission denied. The /dev/attestation folder is missing in my system.

First of all, it seems you have a running Coordinator and successfully build the Graphene Marble in simulation mode, great!:-)
Let me walk through this:

```
[PreMain] 2021/06/09 19:21:59 failed to get quote: open /dev/attestation/user_report_data: permission denied. Proceeding in simulation mode
```

The PreMain detected that no attestation primitive is available and proceeds in simulation mode.

```
[PreMain] 2021/06/09 19:21:59 activating marble of type frontend
panic: open /dev/attestation/protected_files_key: permission denied
```

The error originates from this [code](https://github.com/edgelesssys/marblerun/blob/master/marble/premain/graphene.go#L29). This is something I haven't considered. We currently do not support the protected_files primitive in Graphene with simulation mode. In fact, I'm not sure how Graphene handles them in that case. Unfortunately, the nginx sample uses protected_files, this is the reason it fails.

We could add a workaround. Let me discuss this internally and get back to you.

> Finally, is there some documentation that does a detailed walk-through of the workflow - the sequence of events in the coordinator and the injector?

You can find our docs [here](https://www.marblerun.sh/docs/deployment/standalone/).
There you have walk-throughs for the different Marblerun [deployment types](https://www.marblerun.sh/docs/deployment/standalone/) and for building services with [Graphene](https://www.marblerun.sh/docs/building-services/graphene/).
Please let me know what you'd like to see there that's currently missing?:-)

**Comment by Nirusu** [comment]
Also, let me add:

> The /dev/attestation folder is missing in my system.

Yes, it does not (have to) exist on your real system, but it exists within Graphene.

Normally, you cannot run "normal" Linux applications directly under SGX, as SGX e.g. forbids the use of system calls to keep everything enclosed in an enclave.

Now while this makes sense, it is of course hard to run any normal application without huge porting efforts.

Enter Graphene. Graphene is a so-called library OS, which effectively bridges the enclave with the underlying operation system. Operations which can be performed completely within the enclave stay inside the enclave, and operations which require certain files/responses from the host are bridged through carefully by Graphene.

This means that Graphene also presents a different environment to all the applications running under it. `/dev/attestation` is a virtual device which passes through SGX attestation related features to Graphene, which eventually uses them "on the other side of the wall" to poke the real environment / hardware.

Applications running within Graphene do not see your real filesystem, they see what they have been granted access to (+ some special files/devices, such as the attestation one I mentioned).

**Comment by ratnadeepb** [comment]
@m1ghtym0 I ran the "hello world" example with Graphene. I am running the nginx example as the marblerun repo says (sorry for that confusion). The one part I am kind of missing, and this might be completely on me, is that how exactly is an application ported over? @Nirusu clears up a few things in that regard. Thank you both. The reason I am going through this exercise is because ultimately I want to port over Envoy as a marble and I thought understanding how that happens for nginx could help.

I am also wondering if [this ](https://github.com/edgelesssys/marblerun/blob/master/marble/premain/) is where I should be looking to figure out what premain is doing?

**Comment by m1ghtym0** [comment]
> @m1ghtym0 I ran the "hello world" example with Graphene. I am running the nginx example as the marblerun repo says (sorry for that confusion). The one part I am kind of missing, and this might be completely on me, is that how exactly is an application ported over? @Nirusu clears up a few things in that regard. Thank you both. The reason I am going through this exercise is because ultimately I want to port over Envoy as a marble and I thought understanding how that happens for nginx could help.

I see, thanks for clearing this up. With "porting over" you mean from a regular Graphene enclave to Marblerun?
There a two steps involved:

1. Some configurational changes to the Graphene manifest, you can find them [here](https://www.marblerun.sh/docs/building-services/graphene/). This step can be done automatically [with our CLI](https://www.marblerun.sh/docs/reference/cli/#command-graphene-prepare).
2. Injecting our PreMain code that implements the Marblerun data plane. First, the PreMain [authenticates ](https://www.marblerun.sh/docs/features/attestation/#marble-deployment-and-attestation) with the Coordinator. Then it bootstraps your application in accordance with [what you specified in the Marblerun manifest](https://www.marblerun.sh/docs/workflows/add-service/). Here is the actual "porting-over" part. You need to think about what values/files/keys/certs should be dynamically provisioned by the Coordinator. In a Kubernetes environment most likely you'd normally provision those via ConfigMaps, Secrets, cert-manager, etc. The Marblerun Coordinator essentially makes them trusted. 
 
Hope that clears that up a bit. I've tried to add references to our docs where possible. Please let me know what's missing for you and we can think about adding it to the docs.

> 
> Also, I am trying to deploy the whole thing with kubernetes. I think I am missing a step there.

Sounds good, that's what's Marblerun intended for. Not sure, which step you're referring to?

> I am also wondering if [this ](https://github.com/edgelesssys/marblerun/blob/master/marble/premain/) is where I should be looking to figure out what premain is doing?

We have documentation on the [authentication process](https://www.marblerun.sh/docs/features/attestation/#marble-deployment-and-attestation). The rest is just provisioning the manifest's specification/values. There is also a section in our docs on [that](https://www.marblerun.sh/docs/workflows/define-manifest/).
If your interested in the implementation details here is the [code](https://github.com/edgelesssys/marblerun/blob/master/marble/premain/premain.go#L119) and the [Graphene-specific part](https://github.com/edgelesssys/marblerun/blob/master/marble/premain/graphene.go).

**Comment by m1ghtym0** [comment]
@ratnadeepb Can we close this?

**Comment by ratnadeepb** [comment]
My apologies for the delay in replying.
