### ISSUE TITLE
marblerun-injector nightly release

### ISSUE THREAD

**Issue by 0x161e-swei** [edgelesssys/marblerun#190]
### Use case

Although updates to the marblerun injector are infrequent...in cases of bug fixes like this [commit](https://github.com/edgelesssys/marblerun/pull/183/commits/972bd69885611bc04158d7a2fe1e028c329e7b5f) in  #183,
it would still benefit from a marblerun-injector nightly release, avoiding building images locally.

**Comment by m1ghtym0** [comment]
@0x161e-swei Sure thing! We'll take care of that.

**Comment by m1ghtym0** [comment]
Hi @0x161e-swei, we already had a nightly image of the marble-injector but there was a problem in our pipeline.
Should be fixed now. Sorry about that!
