### ISSUE TITLE
[OpenEnclave] OpenEnclave emits `ERROR: OE_UNSUPPORTED` messages in simulation mode

### ISSUE THREAD

**Issue by dimakuv** [edgelesssys/marblerun#219]
### Issue description

When running the Coordinator in simulation mode, I see a bunch of error messages from OpenEnclave like this:
```
$ OE_SIMULATION=1 erthost build/coordinator-enclave.signed
[get_qpl_handle ../qe_logic.cpp:295] Failed to set logging callback for the quote provider library.[get_qpl_handle ../qe_logic
.cpp:295] Failed to set logging callback for the quote provider library.[get_qpl_handle ../qe_logic.cpp:295] Failed to set log
ging callback for the quote provider library.2021-07-19T23:52:54-0700.880296Z [(E)ERROR] tid(0x7f324d39a700) | coordinator-enc
lave.signed::OE_UNSUPPORTED [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:s
gx_create_report:131]
2021-07-19T23:52:54-0700.880333Z [(E)ERROR] tid(0x7f324d39a700) | coordinator-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:_get_local_report:189]
2021-07-19T23:52:54-0700.880354Z [(E)ERROR] tid(0x7f324d39a700) | coordinator-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:oe_get_remote_report:294]
2021-07-19T23:52:54-0700.880372Z [(E)ERROR] tid(0x7f324d39a700) | coordinator-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:_oe_get_report_internal:388]
2021-07-19T23:52:54-0700.880396Z [(E)ERROR] tid(0x7f324d39a700) | coordinator-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:oe_get_report_v2_internal:443]
2021-07-19T23:52:54-0700.880422Z [(E)ERROR] tid(0x7f324d39a700) | coordinator-enclave.signed:SGX Plugin _get_report(): failed
to get ecdsa report. OE_UNSUPPORTED (oe_result_t=OE_UNSUPPORTED) [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openen
clave-src/enclave/sgx/attester.c:_get_report:320]
2021-07-19T23:52:54-0700.880442Z [(E)ERROR] tid(0x7f324d39a700) | coordinator-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/sgx/report.c:oe_get_report_v2:192]
```

Similar errors are seen for Marbles (server, client):
```
$ EDG_MARBLE_TYPE=server EDG_MARBLE_UUID_FILE=$PWD/server_uuid EDG_TEST_ADDR=localhost:8001 OE_SIMULATION=1 erthost build/marble-test-enclave.signed
[PreMain] 2021/07/20 06:55:25 generating quote
[get_qpl_handle ../qe_logic.cpp:295] Failed to set logging callback for the quote provider library.[get_qpl_handle ../qe_logic
.cpp:295] Failed to set logging callback for the quote provider library.[get_qpl_handle ../qe_logic.cpp:295] Failed to set log
ging callback for the quote provider library.2021-07-19T23:55:25-0700.250956Z [(E)ERROR] tid(0x7f11cc78f700) | marble-test-enc
lave.signed::OE_UNSUPPORTED [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:s
gx_create_report:131]
2021-07-19T23:55:25-0700.250982Z [(E)ERROR] tid(0x7f11cc78f700) | marble-test-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:_get_local_report:189]
2021-07-19T23:55:25-0700.250999Z [(E)ERROR] tid(0x7f11cc78f700) | marble-test-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:oe_get_remote_report:294]
2021-07-19T23:55:25-0700.251014Z [(E)ERROR] tid(0x7f11cc78f700) | marble-test-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:_oe_get_report_internal:388]
2021-07-19T23:55:25-0700.251029Z [(E)ERROR] tid(0x7f11cc78f700) | marble-test-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/core/sgx/report.c:oe_get_report_v2_internal:443]
2021-07-19T23:55:25-0700.251050Z [(E)ERROR] tid(0x7f11cc78f700) | marble-test-enclave.signed:SGX Plugin _get_report(): failed
to get ecdsa report. OE_UNSUPPORTED (oe_result_t=OE_UNSUPPORTED) [/__w/edgelessrt/edgelessrt/build/3rdparty/openenclave/openen
clave-src/enclave/sgx/attester.c:_get_report:320]
2021-07-19T23:55:25-0700.251067Z [(E)ERROR] tid(0x7f11cc78f700) | marble-test-enclave.signed::OE_UNSUPPORTED [/__w/edgelessrt/
edgelessrt/build/3rdparty/openenclave/openenclave-src/enclave/sgx/report.c:oe_get_report_v2:192]
```

*These errors do not affect the workflow -- everything succeeds and works as expected.*

I installed Edgeless RT v0.2.5 per [its QuickStart package installation](https://github.com/edgelesssys/edgelessrt#quick-start) on Ubuntu 18.04. From what I understand, this package also contains OpenEnclave binaries, so the OpenEnclave version is the one shipped with Edgeless RT v0.2.5. There is no other OpenEnclave installed on my machine.

I also installed the SGX DCAP libraries according to Intel instructions on installing Ubuntu 18.04 packages. My other DCAP-based enclave workloads (e.g., Graphene's `ra-tls-mbedtls`) work well on the same machine.

### To reproduce

1. Install SGX DCAP libraries from Ubuntu 18.04 package installation according to Intel guidelines.
2. Install Edgeless RT v0.2.5 that ships together with OpenEnclave.
3. Build latest commit of Marblerun from sources.
4. Run the example in BUILD file in simulation mode.

### Expected behavior

No ERROR messages from OpenEnclave.

### Environment:
 - Marblerun version:  latest master, commit 3780c0e
 - Edgeless RT version: v0.2.5
 - Go version: go version go1.16.3 linux/amd64
 - Minikube version: N/A

### Additional info / screenshots

I tried to run Marblerun examples in real SGX mode (without `OE_SIMULATION`), and it seems to work fine until OpenEnclave complains about `Out of Date TCB` -- which is fair since my machine has "old" SGX firmware. So it looks like SGX mode works fine. Are these errors that I see some known quirk of OpenEnclave in simulation mode?

Also, feel free to close this issue (since everything works, it's just that these ERROR messages from OE are annoying). I'm just curious why this happens.

**Comment by Nirusu** [comment]
This is expected.

Marblerun itself does not differentiate being launched in simulation mode or non-simulation mode ("SGX mode"), the underlying framework (Edgeless RT / Open Enclave) does. This means that upon launch, Marblerun will try to generate the SGX quote, which of course is not available in simulation mode since we not use SGX there, and thus will fail with "OE_UNSUPPORTED".

So it's not really a bug or an issue, the code knows how to handle this case and continues "in simulation mode", it will just not offer any attestation capabilities. But I agree the error messages are a tad bit annoying to see, maybe we can actually handle this a bit better.

**Comment by dimakuv** [comment]
Thanks @Nirusu, I satisfied my curiosity :) Feel free to close this issue.

**Comment by m1ghtym0** [comment]
@thomasten Can we close this now or do you have more in mind?:-)
