### ISSUE TITLE
[Docs] Describe running Marblerun with AKS, Helm and SGX

### ISSUE THREAD

**Issue by dimakuv** [edgelesssys/marblerun#222]
### Use case

I am trying to run your Kubernetes application (emojivoto) on MS Azure Confidential Computing VMs.

I can do all the stand-alone examples (i.e., non-Kubernetes), and I also understand what happens behind the scenes. I can also do the simulation mode of the emojivoto Kubernetes application with AKS as described in https://www.marblerun.sh/docs/getting-started/quickstart/, but at this point I'm not sure what actually happens.

As a final step, I want to run the same emojivoto Kubernetes application with AKS *and with SGX*, and there are no instructions on how to do this. Moreover, at this point I'm actually lost in all the prerequisites and the details of what's actually happenning behind the CLI commands.

### Describe your solution

Ideally, I would want a tutorial like this one: https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-get-started, but for Marblerun.

I would also very much prefer some descriptions of what Marblerun does exactly with my Kubernetes environment. Like, what does `marblerun install` actually do? Or as another example, in https://www.marblerun.sh/docs/getting-started/quickstart/ in "Step 3: Initialize and verify the Coordinator", we obtain and verify the Marblerun Coordinator's root certificate -- but where is the Coordinator launched, on which Azure VM/resource? I got completely lost at this point.

### Additional context

I would also be happy if you could provide me with some references on how Marblerun "injects" itself in the Kubernetes environment, and how it interaces with other components of the Kubernetes environment (especially the SGX plugins). Probably I'm just too tired today, but I can't wrap my head around the AKS deployment of Marblerun.

**Comment by m1ghtym0** [comment]
Interesting, this seems to be a problem with the `kubectl config`. I'm not entirely sure why this happens but my guess is that there is a different Kubernetes context for the root user present on your system? You might be able to spot the problem by comparing the `kubectl config view` vs. `sudo kubectl config view`.
Either way, you're right we should get rid of the `sudo` and just use a high-numbered port.

**Comment by m1ghtym0** [comment]
Referencing https://github.com/edgelesssys/marblerun.sh/pull/72

**Comment by m1ghtym0** [comment]
@dimakuv What's your opinion on: https://docs.edgeless.systems/marblerun/#/getting-started/quickstart-sgx ?
Regarding AKS prerequisites we have https://docs.edgeless.systems/marblerun/#/deployment/cloud?id=azure-kubernetes-services-aks


> I would also be happy if you could provide me with some references on how Marblerun "injects" itself in the Kubernetes environment, and how it interaces with other components of the Kubernetes environment (especially the SGX plugins). Probably I'm just too tired today, but I can't wrap my head around the AKS deployment of Marblerun.

There is the general [Kubernetes deployment guide](https://docs.edgeless.systems/marblerun/#/deployment/kubernetes) and the [Kubernetes integration](https://docs.edgeless.systems/marblerun/#/features/auto-injection).
Maybe we make too many assumptions about the readers being familiar with Kubernetes concepts and terms?

**Comment by dimakuv** [comment]
The new documentation looks good to me (+ I got more familiar with Kubernetes itself). Closing this issue.
