### ISSUE TITLE
how can one verify if the data in use is indeed confidential?

### ISSUE THREAD

**Issue by nathanawmk** [edgelesssys/marblerun#264]
how can one verify if the data in use is indeed confidential and away from prying eyes? asking this because I am keen to put this in production

**Comment by m1ghtym0** [comment]
Hi @nathanawmk,

Thanks for reaching out!
If your question is on the attestation part of MarbleRun, we have [a section in our doc](https://docs.edgeless.systems/marblerun/#/features/attestation)s explaining our attestation model.
Essentially MarbleRun can give you a concise attestation statement that your whole deployment has integrity and adheres to a predefined manifest.
MarbleRun has nothing to do with how YOUR application handles the data. This is part of your application logic.
MarbleRun expects your application to run in secure enclaves, we call them [Marbles](https://docs.edgeless.systems/marblerun/#/getting-started/marbles). In a Marble your data is confidential and MarbleRun makes it super easy to connect multiple Marbles to a service-based application as you'll find in Kubernetes etc.

If you have more specific questions, please let me know:-)

**Comment by m1ghtym0** [comment]
Thanks again for reaching out, I'll close this issue now.
