### ISSUE TITLE
[ Error ]: can't evaluate field SealKey in type core.reservedSecrets

### ISSUE THREAD

**Issue by piaolaidelangman** [edgelesssys/marblerun#272]
Hi Team. I'm trying to deploy marblerun into our cluster.
## Issue description
While run marblerun according to [build.md](https://github.com/edgelesssys/marblerun/blob/master/BUILD.md#create-a-manifest), while upload manifest.json to the coordinator, get error:
```
{"status":"error","data":null,"message":"in Marble client: env variable SEAL_KEY:
 template: data:1:17: executing \"data\" at \u003c.MarbleRun.SealKey\u003e: 
can't evaluate field SealKey in type core.reservedSecrets"}
```
The coordinator output:
```
127.0.0.1 - - [05/Nov/2021:05:48:36 +0000] "POST /manifest HTTP/2.0" 400 217
```
I skim this step and run the [marbles](https://github.com/edgelesssys/marblerun/blob/master/BUILD.md#run-the-marbles) with command:
```
EDG_MARBLE_TYPE=server EDG_MARBLE_UUID_FILE=$PWD/server_uuid EDG_TEST_ADDR=localhost:8001  erthost build/marble-test-enclave.signed
```
get error:
```
[erthost] loading enclave ...
[erthost] entering enclave ...
[meshentry] invoking premain
[PreMain] 2021/11/05 05:47:56 starting PreMain
[PreMain] 2021/11/05 05:47:56 fetching env variables
[PreMain] 2021/11/05 05:47:56 loading TLS Credentials
[PreMain] 2021/11/05 05:47:56 loading UUID
[PreMain] 2021/11/05 05:47:56 found UUID: f6b2414a-ec07-47ab-a5eb-afe399dae79e
[PreMain] 2021/11/05 05:47:56 generating CSR
[PreMain] 2021/11/05 05:47:56 generating quote
[PreMain] 2021/11/05 05:47:56 activating marble of type server
panic: rpc error: code = FailedPrecondition desc = cannot accept marbles in current state

goroutine 17 [running, locked to thread]:
main.ert_meshentry_premain(0x7f1ee21e6680, 0x7f1ee21e6678)
        /home/diankun/Apps/marblerun/cmd/marble-test/mesh.go:27 +0x19d
```
The coordinator output:
```
{"level":"warn","ts":1636091252.6747434,"caller":"zap/options.go:203","msg":"finished unary call with code FailedPrecondition","grpc.start_time":"2021-11-05T05:47:32Z","system":"grpc","span.kind":"server","grpc.service":"rpc.Marble","grpc.method":"Activate","peer.address":"127.0.0.1:58298",
"error":"rpc error: code = FailedPrecondition desc = cannot accept marbles in current state","grpc.code":"FailedPrecondition","grpc.time_ms":0}
```
## Environment
* Marblerun version: latest master, commit [c270a92](https://github.com/edgelesssys/marblerun/commit/c270a92a2998a25415c56203446e0bcb6e867980)
* Edgeless RT version: latest master, commit [823c7ed](https://github.com/edgelesssys/edgelessrt/commit/823c7edbd8d5ff1d531511e2e98a3dea0dafee5c)
* Ubuntu 20.04
* With Intel Sgx

Thanks!

**Comment by m1ghtym0** [comment]
Thanks, @piaolaidelangman for reaching out.
The manifest in the build.md still contains a `MarbleRun.SealKey` env variable, which was removed with https://github.com/edgelesssys/marblerun/pull/238.
You can just remove the lines `"SEAL_KEY": "{{ hex .MarbleRun.SealKey }}"` from your manifest.
Sorry about that, I'll remove that asap.

Your Marbles won't be able to boot until a manifest has been set. So the second error is expected.

**Comment by piaolaidelangman** [comment]
Thanks, @m1ghtym0 it works. But in the net step:
 ```
EDG_MARBLE_TYPE=server EDG_MARBLE_UUID_FILE=$PWD/server_uuid EDG_TEST_ADDR=localhost:8001  erthost build/marble-test-enclave.signed
```
get error:
```
[erthost] loading enclave ...
[erthost] entering enclave ...
[meshentry] invoking premain
[PreMain] 2021/11/05 06:51:26 starting PreMain
[PreMain] 2021/11/05 06:51:26 fetching env variables
[PreMain] 2021/11/05 06:51:26 loading TLS Credentials
[PreMain] 2021/11/05 06:51:26 loading UUID
[PreMain] 2021/11/05 06:51:26 found UUID: f6b2414a-ec07-47ab-a5eb-afe399dae79e
[PreMain] 2021/11/05 06:51:26 generating CSR
[PreMain] 2021/11/05 06:51:26 generating quote
[PreMain] 2021/11/05 06:51:26 activating marble of type server
panic: rpc error: code = Unauthenticated desc = invalid quote

goroutine 17 [running, locked to thread]:
main.ert_meshentry_premain(0x7fe8621e6680, 0x7fe8621e6678)
        /home/diankun/Apps/marblerun/cmd/marble-test/mesh.go:27 +0x19d
```
The coordinator output:
```
{"level":"info","ts":1636095086.6122756,"caller":"core/marbleapi.go:55","msg":"Received activation request","MarbleType":"server"}
ERROR: :OE_JSON_INFO_PARSE_ERROR [openenclave-src/common/sgx/tcbinfo.c:oe_parse_tcb_info_json:789]
ERROR: Failed to parse TCB info. OE_JSON_INFO_PARSE_ERROR (oe_result_t=OE_JSON_INFO_PARSE_ERROR) [openenclave-src/common/sgx/collateral.c:oe_validate_revocation_list:418]
ERROR: :OE_INVALID_PARAMETER [openenclave-src/enclave/crypto/mbedtls/cert.c:oe_cert_free:713]
ERROR: Failed to validate revocation info. OE_JSON_INFO_PARSE_ERROR (oe_result_t=OE_JSON_INFO_PARSE_ERROR) [openenclave-src/common/sgx/quote.c:oe_get_sgx_quote_validity:774]
ERROR: Failed to validate quote. OE_JSON_INFO_PARSE_ERROR (oe_result_t=OE_JSON_INFO_PARSE_ERROR) [openenclave-src/common/sgx/quote.c:oe_verify_quote_with_sgx_endorsements:629]
{"level":"info","ts":1636095087.5042908,"caller":"zap/options.go:203",
"msg":"finished unary call with code Unauthenticated","grpc.start_time":"2021-11-05T06:51:26Z","system":"grpc","span.kind":"server","grpc.service":"rpc.Marble","grpc.method":"Activate",
"peer.address":"127.0.0.1:58302",
"error":"rpc error: code = Unauthenticated desc = invalid quote","grpc.code":"Unauthenticated","grpc.time_ms":892.0150146484375}
```
Thanks!

**Comment by daniel-weisse** [comment]
Hi @piaolaidelangman , could you tell us in what environment you are running this under?
Are you running in Azure, Alibaba Cloud, your own SGX setup etc.?
What quote provider library are you using? `az-dcap-client`, `libsgx-dcap-default-qpl` or something else?

If you are using `libsgx-dcap-default-qpl` could you share with us your PCCS config in `/etc/sgx_default_qcnl.conf` ?

**Comment by piaolaidelangman** [comment]
Hi @daniel-weisse , Thanks for your reply.
I'm running in Alibaba Cloud and my quote provider library is `libsgx-dcap-default-qpl`,  the config in `/etc/sgx_default_qcnl.conf` is:
```
# PCCS server address
PCCS_URL=https://sgx-dcap-server.cn-shanghai.aliyuncs.com/sgx/certification/v3/

# To accept insecure HTTPS certificate, set this option to FALSE
USE_SECURE_CERT=TRUE

# You can use Intel PCS to get quote verification collateral
#COLLATERAL_SERVICE=https://api.trustedservices.intel.com/sgx/certification/v3/

# If you use PCCS service to get quote verification collateral, you can specify which API version is to be used
# The legacy 3.0 API will return CRLs in HEX encoded DER format, while the new 3.1 API will return raw DER format
#PCCS_API_VERSION=3.1

# Maximum retry times for QCNL. If RETRY is not defined or set to 0, no retry will be performed.
# It will first wait one second and then for all forthcoming retries it will double the waiting time
# By using RETRY_DELAY you disable this exponential backoff algorithm
#RETRY_TIMES=6

# Sleep this amount of seconds before each retry when a transfer has failed with a transient error
#RETRY_DELAY=10
```
Thanks !

**Comment by daniel-weisse** [comment]
It seems Alibaba Cloud updated their PCCS infrastructure since the last time I checked.
If I am not mistaken they are using the default Intel PCCS implementation, which is not yet compatible with [OpenEnclave](https://github.com/openenclave/openenclave) (the library we use to verify quotes).

For testing purposes you can use our PCCS docker image, which implements the same functionality as the Alibaba PCCS.
You can find details about the image [here](https://github.com/edgelesssys/era/tree/master/pccs).

To run the image you need an Intel SGX API key: https://api.portal.trustedservices.intel.com/provisioning-certification
Once you have one, you can run the image:
```shell
docker run -e APIKEY=<your-API-key> -p 8081:8081 --name pccs -d ghcr.io/edgelesssys/pccs
```

You will have to adjust your config in `/etc/sgx_default_qcnl.conf`:
```
# PCCS is running on localhost
PCCS_URL=https://localhost:8081/sgx/certification/v3/

# Set USE_SECURE_CERT to false to accept self signed PCCS certificates
USE_SECURE_CERT=FALSE
```

**Comment by piaolaidelangman** [comment]
Thanks! I will give it a try right now.

**Comment by piaolaidelangman** [comment]
Thanks, it works!
But I get a question: the Alibaba's PCCS is incompatible with open enclave, but the coordinator can start before I run the PCCS image. Who varifys the coordinator's quote?

**Comment by daniel-weisse** [comment]
Verifying the Coordinator is up to the user.
Using the MarbleRun CLI, the Coordinator's quote is verified every time the CLI accesses the Coordinator's REST API.
For example when running `marblerun set manifest manifest.json <COORDINATOR_ADDR>`,  the CLI will verify the quote and only send the manifest if the verification is successful.

Alternatively, the quote can also be verified manually using the [era tool](https://github.com/edgelesssys/era).

**Comment by piaolaidelangman** [comment]
I see. Thanks again! Feel free to close this issue.

**Comment by daniel-weisse** [comment]
Looked over it again:
The latest PCCS version is supported by MarbleRun, which means in theory Alibaba's PCCS should be too.
However OpenEnclave fails to parse some JSON data correctly, which results in the errors we see here.

Should not be too hard to fix. Relevant Issue in the OpenEnclave repo: https://github.com/openenclave/openenclave/issues/4308
