### ISSUE TITLE
TLS credentials in a specific location

### ISSUE THREAD

**Issue by sudharkrish** [edgelesssys/marblerun#280]
Note: I am new to marble-run. I have some questions, for my feature-request below, it appears this may be already supported, so
I may just need some pointers on how to enable my use-case described below.

### Use case
Following steps here-> https://github.com/edgelesssys/marblerun/blob/master/BUILD.md

I am able to run the co-ordinator and marbles(server and client ) in simulation mode.

Question-> Does this example use transparent TLS, does the marble-run co-ordinator send the private-key and cert and Root-CA-cert to the mables(server, and client). And do the marbles-> server and client, do a handshake and perform mutual TLS authentication to verify each-other's certificates while establishing TLS session.

Question->If all above assumptions are correct, is it possible to do the above using marbles(built using Ego), and can those marble applications get their TLS credentials(private-key, cert, and RootCA-cert) from co-ordinator put in a specific location specified by the marble’s config file.

### Additional context
Use-Case Details-> In our use-case(currently only need stand-alone deployment of marble-run), we just need co-ordinator to do the SGX attestation, and send TLS credentials to a specific location specified in marble’s config file, so that later, marble applications(Go application built using Ego) can use those TLS credentials(sent by co-ordinator) to establish a DTLS session(TLS-like protocol over UDP) between their peers.

**Comment by daniel-weisse** [comment]
>Question-> Does this example use transparent TLS, does the marble-run co-ordinator send the private-key and cert and Root-CA-cert to the mables(server, and client). And do the marbles-> server and client, do a handshake and perform mutual TLS authentication to verify each-other's certificates while establishing TLS session.

Yes and no: [Transparent TLS](https://docs.edgeless.systems/marblerun/#/features/transparent-TLS) is a feature for Marbles built with EGo, which allows wrapping connections with TLS. The actual applications do not need to know how to speak TLS or know that they speak TLS at all.
The Marble to Coordinator connections uses TLS, however the Marble does not verify the Coordinator (the Marble has no way of verifying the Coordinator's certificate).

Saving the TLS credentials to a specific location is possible.
Take a look at the [defining a manifest section](https://docs.edgeless.systems/marblerun/#/features/transparent-TLS) of our docs for detailed information.
You can save a file to a specific location by setting the filename. The following example saves the MarbleRun CA cert, the Marble's private key and the Marble's certificate to the folder `/var/tls/`
```javascript
{
    // ...
    "Marbles": {
        "exampleMarble": {
            "Package": "example",
            "Parameters": {
                "Files": {
                    "/var/tls/marblerun_root_ca.pem": "{{  pem .MarbleRun.RootCA.Cert  }}",
                    "/var/tls/marble_cert.pem" : "{{ pem .MarbleRun.MarbleCert.Cert }}",
                    "/var/tls/marble_priv_key.pem": "{{ pem .MarbleRun.MarbleCert.Private }}"
                }
            }
        }
    }
    //...
}
```
You are also not limited to just the default certificates issued by the Coordinator. If you application requires it, you can define your own and customize them to your needs, for more details see [here](https://docs.edgeless.systems/marblerun/#/workflows/define-manifest?id=secrets).
[This example](https://github.com/edgelesssys/edgelessdb-marblerun-demo/blob/master/marblerun-manifest.json) shows a manifest which creates certificates and stores them as environment variable.

**Comment by sudharkrish** [comment]
Thanks for all the info @daniel-weisse. Will close this, and check-back thro discord channel, if there any questions.
