### ISSUE TITLE
Marble run co-ordinator using SGX DCAP for quote verification

### ISSUE THREAD

**Issue by sudharkrish** [edgelesssys/marblerun#281]
### Issue description
Note: I am new to marble-run. I think have a setup or configuration issue, and not a real issue, but need some pointers in resolving it.
I am trying to setup marble-run co-ordinator to use Intel SGX DCAP based attestation for quote verification but running into issue, 
when co-ordinator launches. 
ERROR: sgxquoteprovider: libdcap_quoteprov.so libdcap_quoteprov.so: cannot open shared object file: No such file or directory [openenclave-src/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:81]
ERROR: oe_initialize_quote_provider failed (oe_result_t=OE_QUOTE_PROVIDER_LOAD_ERROR) [openenclave-src/host/sgx/sgxquoteprovider.c:oe_initialize_quote_provider:48]
ERROR: SGX Plugin _get_report(): failed to get ecdsa report. OE_QUOTE_PROVIDER_LOAD_ERROR 

Any suggestions to resolve the above error as well as some of my questions below would be helpful.

I tried setting up local PCCS server, as per info here->(https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md ), but ran into setup issues.

I read the info PCCS setup info options here-> https://docs.edgeless.systems/marblerun/#/deployment/on-prem?id=sgx-datacenter-attestation-primitives-dcap

I was wondering, if marble-run has any automated(default option) way of using public PCCS service(provided by Alibaba or Azure), that can be used without the user having to set up the PCCS server.

My current understanding is that, if user does not setup a local PCCS server or if user does not use a public PCCS service, then marble-run co-ordinator does not have any way of verifying SGX quotes.

### To reproduce
Link-> https://docs.edgeless.systems/marblerun/#/deployment/standalone

Installed EdgelessRT, as per info here-> https://github.com/edgelesssys/edgelessrt#quick-start
Also installed SGX packages are per info here-> https://github.com/edgelesssys/edgelessrt#sgx-packages
(sudo apt install libsgx-dcap-ql-dev libsgx-enclave-common libsgx-launch)

And then when I launched co-ordinator got the error below…-> ERROR: sgxquoteprovider: libdcap_quoteprov.so libdcap_quoteprov.so: cannot open shared object file: No such file or directory 

Logs below:

sudha@a4bf0170dc2d:~/marble-coord$ erthost coordinator-enclave.signed
[erthost] loading enclave ...
[erthost] entering enclave ...
[meshentry] invoking premain
[meshentry] invoking main
{"level":"info","ts":1638960815.8947709,"caller":"coordinator/run.go:50","msg":"starting coordinator","version":"0.5.1","commit":"f4644183f8b34ceabfbcfb7a4dbd4d7087055b3d"}
{"level":"info","ts":1638960815.8947709,"caller":"coordinator/run.go:79","msg":"creating the Core object"}
{"level":"info","ts":1638960815.8947709,"caller":"core/core.go:134","msg":"loading state"}
{"level":"info","ts":1638960815.898771,"caller":"core/core.go:172","msg":"No sealed state found. Proceeding with new state."}
{"level":"info","ts":1638960815.926771,"caller":"core/core.go:329","msg":"generating quote"}
ERROR: sgxquoteprovider: libdcap_quoteprov.so libdcap_quoteprov.so: cannot open shared object file: No such file or directory [openenclave-src/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:81]
ERROR: oe_initialize_quote_provider failed (oe_result_t=OE_QUOTE_PROVIDER_LOAD_ERROR) [openenclave-src/host/sgx/sgxquoteprovider.c:oe_initialize_quote_provider:48]
ERROR: SGX Plugin _get_report(): failed to get ecdsa report. OE_QUOTE_PROVIDER_LOAD_ERROR (oe_result_t=OE_QUOTE_PROVIDER_LOAD_ERROR) [openenclave-src/enclave/sgx/attester.c:_get_report:320]
{"level":"fatal","ts":1638960815.926771,"caller":"coordinator/run.go:86","msg":"Cannot create Coordinator core","error":"failed to get quote: OE_QUOTE_PROVIDER_LOAD_ERROR","stacktrace":"main.run\n\tgithub.com/edgelesssys/marblerun/cmd/coordinator/run.go:86\nmain.main\n\tgithub.com/edgelesssys/marblerun/cmd/coordinator/enclavemain.go:29\nmain.invokemain\n\tgithub.com/edgelesssys/marblerun/cmd/coordinator/invokemain.go:15\n_cgoexp_2210a7c57b2b_invokemain\n\t_cgo_gotypes.go:39\nruntime.cgocallbackg1\n\truntime/cgocall.go:292\nruntime.cgocallbackg\n\truntime/cgocall.go:228\nruntime.cgocallback\n\truntime/asm_amd64.s:788"}

### Environment:
 - MarbleRun version: Downloaded latest from here -->https://github.com/edgelesssys/marblerun/releases/latest/download/coordinator-enclave.signed
 - Edgeless RT version: edgelessrt_0.2.10_amd64.deb
 - Go version: 1.15.5
 - Minikube version:

### Additional info / screenshots
For example, if someone uses the Marblerun co-ordinator docker image-> https://github.com/edgelesssys/marblerun/pkgs/container/coordinator, it will be a nice, if  it can automatically(default option) use any public PCCS service..for verifying SGX quotes.

Any suggestions to resolve the above error reported(ERROR: sgxquoteprovider: libdcap_quoteprov.so libdcap_quoteprov.so: cannot open shared object file: No such file or directory [openenclave-src/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:81] ), as well as for some of my questions would be helpful.

**Comment by daniel-weisse** [comment]
Hi @sudharkrish ,
The problem you are facing comes from a missing quote-provider-library (mentioned [here](https://docs.edgeless.systems/marblerun/#/deployment/on-prem?id=sgx-datacenter-attestation-primitives-dcap) in the on-prem)).
This library is provides an interface for the application to talk to the PCCS you set up.

Depending on your environment you have two multiple options:
* If you are using a VM with Intel SGX support provided by Azure, you can use the `az-dcap-client` which is configured to talk to the public Azure PCCS. Installation instructions can be found [here](https://docs.edgeless.systems/marblerun/#/deployment/cloud?id=azure-confidential-computing-vms)
* If you are using a VM with Intel SGX support provided by Alibaba Cloud, you should be able to use the public Alibaba PCCS. and the Intel default quote-provider-library, configured to talk to the PCCS. Installation instructions can be found [here](https://docs.edgeless.systems/marblerun/#/deployment/cloud?id=alibaba-cloud-elastic-compute-service).  However, there is currently an [issue](https://github.com/edgelesssys/marblerun/issues/272#issuecomment-968981571) which prevents proper quote verification
* If you are using your own infrastructure, or a cloud which does not host its own PCCS, you will need to set up the PCCS yourself, as well as configure a quote-provider-library to talk to your PCCS. You can find a guide [here](https://docs.edgeless.systems/marblerun/#/deployment/cloud?id=alibaba-cloud-elastic-compute-service).

As for the docker image automatically choosing a public PCCS:
By default the image will use Azure's `az-dcap-client` which connects to Azure's PCCS. However, quote verification with Azure's PCCS is only possible if the quote was also generated on Azure's infrastructure. So you can't really use it if you are running your SGX workloads on your own hardware.
If you set the environment variable `DCAP_LIBRARY=intel`, the Coordinator will instead use Intel's default quote-provider-library, you can mount a configuration file to `/etc/sgx_default_qcnl.conf` to [configure the library to talk to your PCCS](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/qpl/README.md#configuration)

**Comment by sudharkrish** [comment]
Hi @daniel-weisse thanks for all the info. I also came across this link->https://github.com/edgelesssys/marblerun/issues/272#issuecomment-964086543, where they mention about a PCCS docker image(which implements the same functionality as the Alibaba PCCS) that can be used for test-purpose. Do you happen to know, if this is a full-fledged PCCS, that can talk to Intel's PCS server to fetch the certificates(and then cache it locally in pckcache.db), and then whether this test PCCS can be used by Marble-run co-ordinator to verify SGX quotes. Also on a side-note, I am trying this on a Intel-SGX pre-production server.

**Comment by daniel-weisse** [comment]
Yes, the docker image is a complete PCCS. It is essentially the PCCS as describe in [the Intel SGX repo](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md) wrapped with an init script for easier usage.
Full setup guide [here](https://github.com/edgelesssys/era/tree/master/pccs)

As for pre-production systems I am not sure, but it should work. Let us know if you run into any issues!

**Comment by sudharkrish** [comment]
Thanks for all the info @daniel-weisse. Will close this, and check-back thro discord channel, if there any questions.
