### ISSUE TITLE
MarbleRun CLI in zsh doesn't run on MacOS Monterey

### ISSUE THREAD

**Issue by brunocous** [edgelesssys/marblerun#284]
### Issue description
After running 
```
wget -P ~/.local/bin https://github.com/edgelesssys/marblerun/releases/latest/download/marblerun
chmod +x ~/.local/bin/marblerun
marblerun
```
it complains that it can't run `marblerun`.
> zsh: exec format error: marblerun

I also tried in bash, resulting in the same type of error
> bash: /usr/local/bin/marblerun: cannot execute binary file: Exec format error

### To reproduce

1. Install CLI on MacOS Monterey according to quickstart guide.
2. Run `marblerun`.

### Expected behavior
That it actually runs out of the box on supported OS's.

### Environment:
 - MarbleRun version: 0.5.1 (latest)
 - MacOS version: 12.0.1
 - processor: 2,6 GHz 6-Core Intel Core i7 on 2019 MBP
 - zsh version: 5.8
 - bash version: 5.1.8

### Additional info / screenshots
After running `file marblerun`:
> marblerun: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=fjDIVdyx3VX74VxmXi0t/_SltzS5gZdvIAdG-fTED/fmjMr2R44PiWAUHhJCVB/EEP2iHpxqC4dfyKBUskP, BuildID[sha1]=7ba217f4d5c643057854205bbe6bdf94a6a8dbd5, not stripped

After running `go env`:
> GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/XX/Library/Caches/go-build"
GOENV="/Users/XX/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/XX/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/XX/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z5/lymq6hy12yj2g7t58d1237h40000gn/T/go-build2730943917=/tmp/go-build -gno-record-gcc-switches -fno-common"

I suspect it was not compiled for Mac. 

### workarounds
Run it inside a Docker container or local VM that support 32bit executables. Or building it myself.

**Comment by m1ghtym0** [comment]
Hey @brunocous did you get it to work on Mac OS or did you switch to using Linux/Ubuntu?
