### ISSUE TITLE
Attempting to deploy Marblerun in minikube on Azure SGX VM

### ISSUE THREAD

**Issue by chigarovae** [edgelesssys/marblerun#285]
Hi! I'm currently trying to deploy Marblerun in minikube cluster on Azure SGX VM.

Host itself has the following SGX devices:

`/dev/sgx`
`/dev/sgx_enclave`
`/dev/sgx_provision`

When attempting to deploy SGX plugin i first have to comment-out host-specific match expressions because they don't contain minikube by default, after that plugin successfully deploys and _marblerun precheck_ says that cluster is SGX-enabled and fits Marblerun requirements.

But once i run _marblerun install_ and check deployed pods i see that coordinator pod fails to start with the following error:

`Error: failed to start container "coordinator": Error response from daemon: error gathering device information while adding custom device "/dev/sgx": not a device node`

I tried to mount all available SGX devices with SGX plugin with the same result. Is there any suggestion how can it be done?

Thanks in advance!

**Comment by daniel-weisse** [comment]
Hi @chigarovae ,
`/dev/sgx/provision` and `/dev/sgx/enclave` are symlinks to `/dev/sgx_enclave` and `/dev/sgx_provision`, and there seems to be some issues with minikube and the available device plugins handling this properly. 

Assuming your Azure VM is running Ubuntu with kernel version 5.11 or newer you should be able to get it working the following way:
``` shell
# Start minikube and wait for everything to start
minikube start --mount --mount-string /dev/sgx/:/dev/sgx/

# Install cert-manager (required by the Intel SGX device plugin)
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.3/cert-manager.yaml

# Wait until cert-manager is finished setting up, then install the Intel SGX device plugin
kubectl apply -k https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/sgx_plugin/overlays/epc-nfd/?ref=main
```

Let us know if this works for you or if there are any issues!

**Comment by chigarovae** [comment]
@daniel-weisse Thanks for your response! On the plugin line got this error:

`error: AccumulateTarget: couldn't make target for https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.10.0: json: unknown field "components"`

**Comment by daniel-weisse** [comment]
I am using minikube v1.23.2 and kubectl v1.22.2.
Also tested this successfully with minikube v1.25.1 and kubectl v1.23.2.

**Comment by chigarovae** [comment]
@daniel-weisse Thanks! After some experiments with versions made it work. Closing this issue.
