### ISSUE TITLE
Coordinator API - endpoint for manifest signature

### ISSUE THREAD

**Issue by lead4good** [edgelesssys/marblerun#290]
### Use case
Attestation in air gapped environments is currently not possible if the coordinator API is not part of that environment. Without the secure and attested connection to the API it is not possible to attestate the manifest.

### Describe your solution
The coordinator attestation report, the PKI chain and the manifest can be distributed to an air gapped environment easily. What is missing is a manifest signature that links the PKI chain to the manifest and hence to the attestation report. The intermediate key should be used to sign the manifest to securely handle manifest updates.

### Additional context
For a real world use case imagine trying to attestate marbles from within a blockchain. This is currently not possible as the blockchain itself cannot access the coordinator API.

**Comment by m1ghtym0** [comment]
Thank you @lead4good, this sounds useful!
Would you be interested to contribute the implementation?

**Comment by lead4good** [comment]
@m1ghtym0 Could be. Let me check with the stakeholders what priority this feature has.

**Comment by lead4good** [comment]
@m1ghtym0 I've received the OK from the stakeholders.

Let me describe the implementation I have in mind.
The coordinators `manifest/get` [endpoint](https://github.com/edgelesssys/marblerun/blob/590f82fcd4bd6885ecdd22037b243c82fdc992a1/coordinator/server/client_api.go#L104-L110) already returns the base64 encoded manifest plus a hash of the manifest. I would append this endpoint to also return another value, which will be the hashes signature - signed by the intermediate key.
```
rsa.SignPKCS1v15(rand.Reader, intermediate.PrivateKey, crypto.SHA256, manifest_hash)
## equivalent to
openssl dgst -sha256 -binary -sign intermediate.pem manifest.json | base64
```
I would add this logic in the `GetManifestSignature` [function](https://github.com/edgelesssys/marblerun/blob/590f82fcd4bd6885ecdd22037b243c82fdc992a1/coordinator/core/clientapi.go#L216-L223).

I am not yet sure how to name the signature parameter as a parameter `ManifestSignature` already exists (it returns the hash). To prevent confusion, the hash values parameter name should be `ManifestHash` or `ManifestDigest`, while the signatures parameter name should in fact be `ManifestSignature`. This would introduce breaking changes however.

The steps to verify the signature would then be
```
curl --cacert marblerun.crt "https://$MARBLERUN/manifest" | jq '.data.ManifestSignature' --raw-output | base64 -d > manifest.sig
openssl dgst -verify intermediate_pubkey.pem -signature manifest.sig local_manifest.json
```
