### ISSUE TITLE
Take manifest from cmdline

### ISSUE THREAD

**Issue by aep** [edgelesssys/marblerun#303]
Client is requesting that they went to start marblerun + edb from a single docker compose file.

We will implement this feature but would it be ok to submit it upstream? 

I think it would probably just involve adding a cli flag that takes an initial manifest.

**Comment by m1ghtym0** [comment]
Hi @aep,
Absolutely! We're more than happy to integrate features for different MarbleRun use-cases.
Looking forward to your PR:-)
