### ISSUE TITLE
Query marble launch log from http

### ISSUE THREAD

**Issue by aep** [edgelesssys/marblerun#304]
Client doesn't want to use kubernetes but wants to query the "state" somewhere, meaning the last time a marble was launched. 

We'd implement this using the existing metrics service  just returning an /events endpoint with a list of the relevant log items.

Is this something acceptable upstream?

**Comment by m1ghtym0** [comment]
Same here. Sounds like a useful metric to have. Current metrics are what we needed so far for benchmarking, With metrics, we need to evaluate if that could cause information leaks in any way. "marble launch count" though is totally fine. Looking forward to your PR:-)
