### ISSUE TITLE
distributed confidential computing and data sharing using edgelessdb?

### ISSUE THREAD

**Issue by lijun0314** [edgelesssys/marblerun#311]
Hi, edgelesssys team! 
I'm trying to use edgelessdb in a distributed environment, and now I'm wondering If use [marblerun](https://github.com/edgelesssys/marblerun), deploy multiple edgelessdb services in a distributed environment, i.e. edgelessdb A, B, C.
For edgelessdb A, B, and C:
Firstly, can A, B, and C interact securely? From MarbleRun's documentation, I found that the communication between multiple services is encrypted.
Secondly, can A, B, and C data be synchronized in real-time? Is it possible to implement database backup in marblerun?
Looking forward to your reply.

**Comment by m1ghtym0** [comment]
Hi @lijun0314,
MarbleRun can be used to establish secure connections between EDB instances.
However, synchronization between EDB instances is not supported atm, hence, you wouldn't gain much doing so.
MarbleRun has no specific database backup functionality for EDB. You can use MarbleRun to manage the backup keys for you though.

**Comment by lijun0314** [comment]
Hi, @m1ghtym0 , thanks for your reply!
Using Marblerun to manage the backup key is one solution, I will learn Marblerun first and then do so.
