### ISSUE TITLE
Target "openenclave::ertmeshentry" not found during cmake setup

### ISSUE THREAD

**Issue by andre-w-fischer** [edgelesssys/marblerun#315]
### Issue description

CMake fails to produce a Makefile because of a missing dependency "openenclave::ertmeshentry" for target "marble-test-enclave".

Full output is
```
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
-- Check for working C compiler: /usr/bin/clang-10
-- Check for working C compiler: /usr/bin/clang-10 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-10
-- Check for working CXX compiler: /usr/bin/clang++-10 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for crypto library - found
-- Looking for dl library - found
-- Performing Test OE_SPECTRE_MITIGATION_C_FLAGS_SUPPORTED
-- Performing Test OE_SPECTRE_MITIGATION_C_FLAGS_SUPPORTED - Success
-- Performing Test OE_SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED
-- Performing Test OE_SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED - Success
-- Configuring done
CMake Error at CMakeLists.txt:105 (add_executable):
  Target "marble-test-enclave" links to target "openenclave::ertmeshentry"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:105 (add_executable):
  Target "marble-test-enclave" links to target "openenclave::ertmeshentry"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

### To reproduce

1. `mkdir build`
2. `cd build`
3. `CC=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 cmake ..`

### Expected behavior

CMake finishes without error.

### Environment

- MarbleRun version: Commit 65978b0085be1759b70e3a0083f89725fac7f773, Thu Aug 25 08:21:42 2022 +0200
- Edgeless RT version: Built from source. Commit 4894b31b918e3b129aa1cbf96b366bea398c2085, tag: v0.3.5, Thu Aug 18 12:21:34 2022 +0200
- Go version: go version go1.19 linux/amd64

- ~~Minikube~~ MicroK8s version:
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.3-2+63243a96d1c393", GitCommit:"63243a96d1c3932c704cf0625f5834411bc3b2e6", GitTreeState:"clean", BuildDate:"2022-07-19T17:59:47Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.3-2+63243a96d1c393", GitCommit:"63243a96d1c3932c704cf0625f5834411bc3b2e6", GitTreeState:"clean", BuildDate:"2022-07-19T17:57:14Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

- CMake version: 3.16.3
 

### Additional info
- I am forcing the use of clang 10 because of the dependency of openenclave on that version.
- I did not find the `ertmeshentry` symbol in a standalone `openenclave` repository. But I can see it in the `edgelessrt` repository. So maybe a clash of different versions of openenclave's standalone version and the one that is nested in `edgelessrt`?

**Comment by thomasten** [comment]
Hi!

> maybe a clash of different versions of openenclave's standalone version and the one that is nested in `edgelessrt`?

Yes, that's quite possible. You must only source Edgeless RT. (By executing `. /opt/edgelessrt/share/openenclave/openenclaverc`). You can check with:
```
echo $CMAKE_PREFIX_PATH
```
This should output
```
:/opt/edgelessrt/lib/openenclave/cmake
```
It may include additional paths, but must not include any additional path to openenclave.

When you got that, delete all files from the build folder and run cmake again.

Btw you can use clang-10 to build MarbleRun, but don't have to. This is only a requirement for building Edgeless RT (inherited from Open Enclave).

**Comment by andre-w-fischer** [comment]
Yes that worked. Sourcing the rc file was the detail that was missing.
Thank you very much.
