### ISSUE TITLE
Marblerun Reproducible Builds

### ISSUE THREAD

**Issue by lead4good** [edgelesssys/marblerun#351]
Can the prebuilt binaries provided as part of Marbleruns [releases](https://github.com/edgelesssys/marblerun/releases) be built deterministically?

If not, has there been investigation into this topic already? Any insights you can share?

**Comment by thomasten** [comment]
This will be added soon, in a similar way as we do for [EGo](https://github.com/edgelesssys/ego/blob/master/dockerfiles/Dockerfile.build) and [EdgelessDB](https://github.com/edgelesssys/edgelessdb/blob/main/Dockerfile).

**Comment by lead4good** [comment]
@thomasten this is great news, looking forward to using this feature
