### ISSUE TITLE
Coordinator failed to boot

### ISSUE THREAD

**Issue by henrysun007** [edgelesssys/marblerun#377]
### Issue description

`sgx.intel.com/enclave` that is necessary for SGX applications to run is missing in the resource request.

### To reproduce

1. Install sgx device plugin according to https://intel.github.io/intel-device-plugins-for-kubernetes/cmd/sgx_plugin/README.html;
2. Run `marblerun install --dcap-qpl intel --dcap-pccs-url https://pccs.example.com/sgx/certification/v3/ --dcap-secure-cert FALSE`.

### Expected behavior

Coordinator enters `crashloopbackoff` state.

### Environment

- MarbleRun version: 1.0.0

**Comment by daniel-weisse** [comment]
Will be fixed in https://github.com/edgelesssys/marblerun/pull/376
